const pageHtml: string = [
  "<!DOCTYPE html>",
  "",
  "<html lang=\"en\"><head>",
  "<meta charset=\"utf-8\"/>",
  "<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\"/>",
  "<title>AetherFlow - Workbench</title>",
  "<script src=\"https://cdn.tailwindcss.com?plugins=forms,container-queries\"></script>",
  "<link href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&amp;display=swap\" rel=\"stylesheet\"/>",
  "<link href=\"https://fonts.googleapis.com/css2?family=Hanken+Grotesk:wght@400;500;600;700&amp;display=swap\" rel=\"stylesheet\"/>",
  "<link href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&amp;display=swap\" rel=\"stylesheet\"/>",
  "<script id=\"tailwind-config\">",
  "        tailwind.config = {",
  "            darkMode: \"class\",",
  "            theme: {",
  "                extend: {",
  "                    \"colors\": {",
  "                        \"primary-container\": \"#0078d4\",",
  "                        \"surface-tint\": \"#0060ab\",",
  "                        \"on-secondary-fixed-variant\": \"#5f00c0\",",
  "                        \"surface-dim\": \"#dadada\",",
  "                        \"surface-bright\": \"#f9f9f9\",",
  "                        \"surface-container-high\": \"#e8e8e8\",",
  "                        \"on-primary-fixed\": \"#001c39\",",
  "                        \"on-primary\": \"#ffffff\",",
  "                        \"inverse-primary\": \"#a3c9ff\",",
  "                        \"on-tertiary-fixed-variant\": \"#005046\",",
  "                        \"on-tertiary-fixed\": \"#00201b\",",
  "                        \"on-tertiary-container\": \"#ffffff\",",
  "                        \"outline-variant\": \"#c0c7d4\",",
  "                        \"surface-container\": \"#eeeeee\",",
  "                        \"primary-fixed-dim\": \"#a3c9ff\",",
  "                        \"on-tertiary\": \"#ffffff\",",
  "                        \"on-error\": \"#ffffff\",",
  "                        \"error-container\": \"#ffdad6\",",
  "                        \"inverse-surface\": \"#2f3131\",",
  "                        \"tertiary-container\": \"#0a8575\",",
  "                        \"error\": \"#ba1a1a\",",
  "                        \"on-primary-container\": \"#ffffff\",",
  "                        \"on-primary-fixed-variant\": \"#004883\",",
  "                        \"outline\": \"#717783\",",
  "                        \"on-surface\": \"#1a1c1c\",",
  "                        \"surface-container-low\": \"#f3f3f3\",",
  "                        \"tertiary-fixed\": \"#91f4e1\",",
  "                        \"secondary\": \"#7615e6\",",
  "                        \"on-surface-variant\": \"#404752\",",
  "                        \"on-secondary-container\": \"#fdf6ff\",",
  "                        \"surface-container-lowest\": \"#ffffff\",",
  "                        \"tertiary-fixed-dim\": \"#75d8c5\",",
  "                        \"background\": \"#f9f9f9\",",
  "                        \"primary-fixed\": \"#d3e3ff\",",
  "                        \"on-secondary\": \"#ffffff\",",
  "                        \"surface\": \"#f9f9f9\",",
  "                        \"tertiary\": \"#006a5c\",",
  "                        \"surface-container-highest\": \"#e2e2e2\",",
  "                        \"secondary-fixed\": \"#ecdcff\",",
  "                        \"primary\": \"#005faa\",",
  "                        \"on-background\": \"#1a1c1c\",",
  "                        \"surface-variant\": \"#e2e2e2\",",
  "                        \"on-secondary-fixed\": \"#270057\",",
  "                        \"secondary-fixed-dim\": \"#d6baff\",",
  "                        \"on-error-container\": \"#93000a\",",
  "                        \"inverse-on-surface\": \"#f1f1f1\",",
  "                        \"secondary-container\": \"#9040ff\"",
  "                    },",
  "                    \"borderRadius\": {",
  "                        \"DEFAULT\": \"0.25rem\",",
  "                        \"lg\": \"0.5rem\",",
  "                        \"xl\": \"0.75rem\",",
  "                        \"full\": \"9999px\"",
  "                    },",
  "                    \"spacing\": {",
  "                        \"unit\": \"4px\",",
  "                        \"max-width\": \"1440px\",",
  "                        \"margin-mobile\": \"16px\",",
  "                        \"gutter\": \"24px\",",
  "                        \"margin-desktop\": \"48px\"",
  "                    },",
  "                    \"fontFamily\": {",
  "                        \"headline-md\": [\"Hanken Grotesk\"],",
  "                        \"headline-lg\": [\"Hanken Grotesk\"],",
  "                        \"display\": [\"Hanken Grotesk\"],",
  "                        \"body-lg\": [\"Hanken Grotesk\"],",
  "                        \"label-sm\": [\"Hanken Grotesk\"],",
  "                        \"headline-lg-mobile\": [\"Hanken Grotesk\"],",
  "                        \"body-md\": [\"Hanken Grotesk\"],",
  "                        \"label-md\": [\"Hanken Grotesk\"]",
  "                    },",
  "                    \"fontSize\": {",
  "                        \"headline-md\": [\"24px\", { \"lineHeight\": \"1.3\", \"fontWeight\": \"600\" }],",
  "                        \"headline-lg\": [\"32px\", { \"lineHeight\": \"1.2\", \"fontWeight\": \"600\" }],",
  "                        \"display\": [\"56px\", { \"lineHeight\": \"1.1\", \"letterSpacing\": \"-0.02em\", \"fontWeight\": \"700\" }],",
  "                        \"body-lg\": [\"18px\", { \"lineHeight\": \"1.6\", \"fontWeight\": \"400\" }],",
  "                        \"label-sm\": [\"12px\", { \"lineHeight\": \"1.4\", \"letterSpacing\": \"0.05em\", \"fontWeight\": \"600\" }],",
  "                        \"headline-lg-mobile\": [\"28px\", { \"lineHeight\": \"1.2\", \"fontWeight\": \"600\" }],",
  "                        \"body-md\": [\"16px\", { \"lineHeight\": \"1.5\", \"fontWeight\": \"400\" }],",
  "                        \"label-md\": [\"14px\", { \"lineHeight\": \"1.4\", \"letterSpacing\": \"0.01em\", \"fontWeight\": \"500\" }]",
  "                    }",
  "                }",
  "            }",
  "        }",
  "    </script>",
  "<style>",
  "        /* Crystal Dewdrop Refraction Classes */",
  "        .glass-panel {",
  "            background: rgba(255, 255, 255, 0.6);",
  "            backdrop-filter: blur(64px);",
  "            -webkit-backdrop-filter: blur(64px);",
  "            border: 1.5px solid rgba(255, 255, 255, 0.5);",
  "            box-shadow:",
  "                0 4px 24px -2px rgba(0, 0, 0, 0.05),",
  "                inset 0 1px 1px rgba(255, 255, 255, 0.8),",
  "                inset 0 -1px 1px rgba(255, 255, 255, 0.2);",
  "        }",
  "        .glass-card {",
  "            background: linear-gradient(135deg, rgba(255,255,255,0.8) 0%, rgba(255,255,255,0.4) 100%);",
  "            backdrop-filter: blur(32px);",
  "            -webkit-backdrop-filter: blur(32px);",
  "            border: 1px solid rgba(255, 255, 255, 0.6);",
  "            box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.04);",
  "            position: relative;",
  "            overflow: hidden;",
  "        }",
  "        .glass-card::before {",
  "            content: '';",
  "            position: absolute;",
  "            top: 0; left: 0; right: 0; bottom: 0;",
  "            background: linear-gradient(135deg, rgba(255,255,255,0.4) 0%, transparent 100%);",
  "            pointer-events: none;",
  "            z-index: 0;",
  "        }",
  "        .glass-card > * {",
  "            position: relative;",
  "            z-index: 1;",
  "        }",
  "",
  "        /* Custom scrollbar for modern feel */",
  "        ::-webkit-scrollbar {",
  "            width: 8px;",
  "            height: 8px;",
  "        }",
  "        ::-webkit-scrollbar-track {",
  "            background: transparent;",
  "        }",
  "        ::-webkit-scrollbar-thumb {",
  "            background: rgba(0, 0, 0, 0.1);",
  "            border-radius: 4px;",
  "        }",
  "        ::-webkit-scrollbar-thumb:hover {",
  "            background: rgba(0, 0, 0, 0.2);",
  "        }",
  "    </style>",
  "</head>",
  "<body class=\"bg-surface-container-lowest text-on-surface flex items-center justify-center min-h-screen p-8\">",
  "<!-- Fixed Presentation Container -->",
  "<div class=\"w-[1280px] h-[1024px] relative overflow-hidden flex rounded-2xl shadow-2xl border border-outline-variant/30 bg-background\">",
  "<!-- Antigravity Particle Background -->",
  "<canvas class=\"absolute inset-0 z-0 pointer-events-none opacity-60\" id=\"particle-canvas\"></canvas>",
  "<!-- SideNavBar (JSON Controlled) -->",
  "<aside class=\"z-20 flex flex-col h-full p-unit gap-gutter w-64 bg-white/80 dark:bg-surface-container/80 backdrop-blur-2xl border-r border-white/40 dark:border-outline-variant/20 shadow-xl shrink-0\">",
  "<!-- Header -->",
  "<div class=\"flex items-center gap-3 px-4 pt-6 pb-2\">",
  "<div class=\"w-10 h-10 rounded-xl bg-gradient-to-br from-primary-container to-primary flex items-center justify-center shadow-md\">",
  "<span class=\"material-symbols-outlined text-white\" style=\"font-variation-settings: 'FILL' 1;\">toys</span>",
  "</div>",
  "<div>",
  "<h2 class=\"font-display text-headline-md font-bold text-primary\">AetherFlow</h2>",
  "<p class=\"font-label-sm text-label-sm text-on-surface-variant opacity-80 uppercase tracking-wider\">Multi-Agent System</p>",
  "</div>",
  "</div>",
  "<!-- CTA -->",
  "<div class=\"px-4 mt-2 mb-4\">",
  "<button class=\"w-full py-3 px-4 bg-primary text-on-primary font-label-md text-label-md rounded-xl shadow-md hover:bg-surface-tint transition-all active:scale-95 flex items-center justify-center gap-2\">",
  "<span class=\"material-symbols-outlined text-[18px]\">add</span>",
  "                    New Agent",
  "                </button>",
  "</div>",
  "<!-- Primary Nav -->",
  "<nav class=\"flex-1 flex flex-col gap-2 px-2\">",
  "<!-- Active Tab -->",
  "<a",
  "  class=\"flex items-center gap-3 px-4 py-3 bg-primary-container/40 dark:bg-primary-container/20 text-primary dark:text-primary-fixed-dim rounded-lg font-bold font-body-md text-body-md hover:translate-x-1 duration-300\"",
  "  href=\"#\">",
  "<span class=\"material-symbols-outlined\">smart_toy</span>",
  "                    Agent Square",
  "                </a>",
  "<!-- Inactive Tabs -->",
  "<a",
  "  class=\"flex items-center gap-3 px-4 py-3 text-on-surface-variant dark:text-on-surface-variant opacity-70 rounded-lg font-body-md text-body-md hover:bg-white/30 dark:hover:bg-surface-container-highest transition-all hover:translate-x-1 duration-300\"",
  "  href=\"#\">",
  "<span class=\"material-symbols-outlined\">chat_bubble</span>",
  "                    Private Chats",
  "                </a>",
  "<a",
  "  class=\"flex items-center gap-3 px-4 py-3 text-on-surface-variant dark:text-on-surface-variant opacity-70 rounded-lg font-body-md text-body-md hover:bg-white/30 dark:hover:bg-surface-container-highest transition-all hover:translate-x-1 duration-300\"",
  "  href=\"#\">",
  "<span class=\"material-symbols-outlined\">groups</span>",
  "                    Group Workspace",
  "                </a>",
  "<a",
  "  class=\"flex items-center gap-3 px-4 py-3 text-on-surface-variant dark:text-on-surface-variant opacity-70 rounded-lg font-body-md text-body-md hover:bg-white/30 dark:hover:bg-surface-container-highest transition-all hover:translate-x-1 duration-300\"",
  "  href=\"#\">",
  "<span class=\"material-symbols-outlined\">folder_open</span>",
  "                    Projects",
  "                </a>",
  "</nav>",
  "<!-- Footer Nav -->",
  "<div class=\"mt-auto px-2 pb-6 flex flex-col gap-2\">",
  "<a",
  "  class=\"flex items-center gap-3 px-4 py-3 text-on-surface-variant dark:text-on-surface-variant opacity-70 rounded-lg font-body-md text-body-md hover:bg-white/30 dark:hover:bg-surface-container-highest transition-all\"",
  "  href=\"#\">",
  "<span class=\"material-symbols-outlined\">cloud</span>",
  "                    Storage",
  "                </a>",
  "<a",
  "  class=\"flex items-center gap-3 px-4 py-3 text-on-surface-variant dark:text-on-surface-variant opacity-70 rounded-lg font-body-md text-body-md hover:bg-white/30 dark:hover:bg-surface-container-highest transition-all\"",
  "  href=\"#\">",
  "<span class=\"material-symbols-outlined\">inventory_2</span>",
  "                    Archive",
  "                </a>",
  "</div>",
  "</aside>",
  "<!-- Main Content Area -->",
  "<div class=\"flex-1 flex flex-col z-10 overflow-hidden relative\">",
  "<!-- TopNavBar (JSON Controlled) -->",
  "<header",
  "  class=\"flex justify-between items-center px-margin-desktop w-full h-16 bg-white/80 dark:bg-surface-container/80 backdrop-blur-xl border-b border-white/40 dark:border-outline-variant/20 shadow-sm shrink-0\">",
  "<!-- Search (on_left) -->",
  "<div class=\"flex-1 max-w-md\">",
  "<div class=\"relative group\">",
  "<span class=\"material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-on-surface-variant group-focus-within:text-primary transition-colors\">search</span>",
  "<input",
  "  class=\"w-full pl-10 pr-4 py-2 bg-surface-container-low border border-outline-variant/50 rounded-full font-body-md text-body-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary transition-all\"",
  "  placeholder=\"Search workspace...\"",
  "  type=\"text\"/>",
  "</div>",
  "</div>",
  "<!-- Actions & Profile -->",
  "<div class=\"flex items-center gap-4\">",
  "<button class=\"p-2 text-on-surface-variant dark:text-on-surface-variant hover:bg-white/20 dark:hover:bg-surface-container-high transition-colors active:scale-95 duration-200 rounded-full relative\">",
  "<span class=\"material-symbols-outlined\">notifications</span>",
  "<span class=\"absolute top-1.5 right-1.5 w-2 h-2 bg-error rounded-full border border-white\"></span>",
  "</button>",
  "<button class=\"p-2 text-on-surface-variant dark:text-on-surface-variant hover:bg-white/20 dark:hover:bg-surface-container-high transition-colors active:scale-95 duration-200 rounded-full\">",
  "<span class=\"material-symbols-outlined\">settings</span>",
  "</button>",
  "<button class=\"p-2 text-on-surface-variant dark:text-on-surface-variant hover:bg-white/20 dark:hover:bg-surface-container-high transition-colors active:scale-95 duration-200 rounded-full\">",
  "<span class=\"material-symbols-outlined\">help</span>",
  "</button>",
  "<div class=\"w-9 h-9 rounded-full bg-gradient-to-tr from-secondary to-primary-container border-2 border-white shadow-sm overflow-hidden cursor-pointer ml-2\">",
  "<img",
  "  alt=\"User profile\"",
  "  class=\"w-full h-full object-cover\"",
  "  data-alt=\"A close up, professional headshot of a young woman with a neutral, focused expression. The lighting is soft and natural, emphasizing a modern, clean corporate aesthetic. She is wearing a simple, high-quality dark top against a slightly blurred, light neutral background that fits seamlessly into a sophisticated enterprise UI.\"",
  "  src=\"https://lh3.googleusercontent.com/aida-public/AB6AXuDPMN2LkyC87uxsoJ4Lbfe6vyX4J8CnSYfwR2YEojRaS34dqrfDKLCo-N13zCKjcwQuhC9m6nR_Egjvrkccp_FOOovUAvjx2Y1PVffdt1lyIUqLQPeTIJZxwUUSSvp6I1vT8PnLyM74Jp6-E73ho-JiRrFKy2z60F1PxMNcyzIwOcHAwRyP_yMxa0-ylGDXP6ypkBKRMzSiAO8iHq5INYjAN5bJ3Is3gFTpaAl7CVjW6Fm5y2Scc14Lpa93jVwr76E_Zp79M686Zzeo\"",
  "/>",
  "</div>",
  "</div>",
  "</header>",
  "<!-- Scrollable Canvas -->",
  "<main class=\"flex-1 overflow-y-auto p-margin-desktop\">",
  "<div class=\"max-w-[1000px] mx-auto flex flex-col gap-8 pb-12\">",
  "<!-- Welcome Header -->",
  "<header class=\"mb-4\">",
  "<h1 class=\"font-display text-display text-on-surface drop-shadow-sm\">欢迎回来，架构师</h1>",
  "<p class=\"font-body-lg text-body-lg text-on-surface-variant mt-2\">您的系统运行平稳。今天有3个智能体处于活跃状态。</p>",
  "</header>",
  "<!-- Main Grid -->",
  "<div class=\"grid grid-cols-12 gap-6\">",
  "<!-- Left Column (8 cols) -->",
  "<div class=\"col-span-12 lg:col-span-8 flex flex-col gap-6\">",
  "<!-- Quick Actions (Bento Box Style) -->",
  "<div class=\"grid grid-cols-2 gap-4\">",
  "<button class=\"glass-card p-6 rounded-2xl flex flex-col items-start gap-4 hover:-translate-y-1 transition-transform duration-300 text-left group\">",
  "<div class=\"w-12 h-12 rounded-full bg-primary/10 flex items-center justify-center text-primary group-hover:scale-110 transition-transform\">",
  "<span class=\"material-symbols-outlined text-[28px]\" style=\"font-variation-settings: 'FILL' 1;\">rocket_launch</span>",
  "</div>",
  "<div>",
  "<h3 class=\"font-headline-md text-headline-md text-on-surface\">部署新智能体</h3>",
  "<p class=\"font-body-md text-body-md text-on-surface-variant mt-1\">从模板配置或从头开始构建</p>",
  "</div>",
  "</button>",
  "<button class=\"glass-card p-6 rounded-2xl flex flex-col items-start gap-4 hover:-translate-y-1 transition-transform duration-300 text-left group\">",
  "<div class=\"w-12 h-12 rounded-full bg-secondary/10 flex items-center justify-center text-secondary group-hover:scale-110 transition-transform\">",
  "<span class=\"material-symbols-outlined text-[28px]\" style=\"font-variation-settings: 'FILL' 1;\">data_exploration</span>",
  "</div>",
  "<div>",
  "<h3 class=\"font-headline-md text-headline-md text-on-surface\">启动新项目</h3>",
  "<p class=\"font-body-md text-body-md text-on-surface-variant mt-1\">创建协作空间与数据管道</p>",
  "</div>",
  "</button>",
  "</div>",
  "<!-- Active Workspace Summary -->",
  "<section class=\"glass-panel p-6 rounded-2xl\">",
  "<div class=\"flex justify-between items-center mb-6\">",
  "<h2 class=\"font-headline-lg text-headline-lg text-on-surface flex items-center gap-2\">",
  "<span class=\"material-symbols-outlined text-primary\">memory</span>",
  "                                        活跃工作区",
  "                                    </h2>",
  "<button class=\"font-label-md text-label-md text-primary hover:underline\">查看全部</button>",
  "</div>",
  "<div class=\"flex flex-col gap-3\">",
  "<!-- Agent Item 1 -->",
  "<div class=\"flex items-center justify-between p-4 rounded-xl bg-white/40 hover:bg-white/60 transition-colors border border-white/50\">",
  "<div class=\"flex items-center gap-4\">",
  "<div class=\"relative\">",
  "<div class=\"w-10 h-10 rounded-lg bg-surface-container-highest flex items-center justify-center text-on-surface\">",
  "<span class=\"material-symbols-outlined\">analytics</span>",
  "</div>",
  "<span class=\"absolute -top-1 -right-1 w-3 h-3 bg-tertiary rounded-full border-2 border-white\"></span>",
  "</div>",
  "<div>",
  "<h4 class=\"font-label-md text-label-md font-bold text-on-surface\">数据分析模型 Alpha</h4>",
  "<p class=\"font-label-sm text-label-sm text-on-surface-variant\">正在处理 Q3 财务报表</p>",
  "</div>",
  "</div>",
  "<div class=\"text-right\">",
  "<span class=\"font-label-md text-label-md text-tertiary\">98% 效率</span>",
  "<div class=\"w-24 h-1.5 bg-surface-container-high rounded-full mt-1 overflow-hidden\">",
  "<div class=\"w-[98%] h-full bg-tertiary rounded-full\"></div>",
  "</div>",
  "</div>",
  "</div>",
  "<!-- Agent Item 2 -->",
  "<div class=\"flex items-center justify-between p-4 rounded-xl bg-white/40 hover:bg-white/60 transition-colors border border-white/50\">",
  "<div class=\"flex items-center gap-4\">",
  "<div class=\"relative\">",
  "<div class=\"w-10 h-10 rounded-lg bg-surface-container-highest flex items-center justify-center text-on-surface\">",
  "<span class=\"material-symbols-outlined\">edit_document</span>",
  "</div>",
  "<span class=\"absolute -top-1 -right-1 w-3 h-3 bg-tertiary rounded-full border-2 border-white\"></span>",
  "</div>",
  "<div>",
  "<h4 class=\"font-label-md text-label-md font-bold text-on-surface\">内容生成器 V2</h4>",
  "<p class=\"font-label-sm text-label-sm text-on-surface-variant\">撰写产品发布博客</p>",
  "</div>",
  "</div>",
  "<div class=\"text-right\">",
  "<span class=\"font-label-md text-label-md text-tertiary\">运行中</span>",
  "<div class=\"w-24 h-1.5 bg-surface-container-high rounded-full mt-1 overflow-hidden\">",
  "<div class=\"w-[65%] h-full bg-tertiary rounded-full\"></div>",
  "</div>",
  "</div>",
  "</div>",
  "</div>",
  "</section>",
  "<!-- Recent Projects Grid -->",
  "<section>",
  "<h2 class=\"font-headline-lg text-headline-lg text-on-surface mb-4\">最近项目</h2>",
  "<div class=\"grid grid-cols-2 gap-4\">",
  "<div class=\"glass-card p-5 rounded-xl border-l-4 border-l-primary\">",
  "<div class=\"flex justify-between items-start mb-4\">",
  "<span class=\"material-symbols-outlined text-primary\">folder_shared</span>",
  "<span class=\"px-2 py-1 bg-primary/10 text-primary font-label-sm text-label-sm rounded-md\">进行中</span>",
  "</div>",
  "<h4 class=\"font-headline-md text-headline-md text-on-surface\">用户留存预测</h4>",
  "<p class=\"font-body-md text-body-md text-on-surface-variant mt-1 mb-4 line-clamp-2\">结合历史行为数据预测下季度流失风险。</p>",
  "<div class=\"flex justify-between items-center text-label-sm font-label-sm text-on-surface-variant\">",
  "<span>最后更新: 2小时前</span>",
  "<div class=\"flex -space-x-2\">",
  "<div class=\"w-6 h-6 rounded-full bg-surface-container-highest border border-white\"></div>",
  "<div class=\"w-6 h-6 rounded-full bg-surface-variant border border-white\"></div>",
  "</div>",
  "</div>",
  "</div>",
  "<div class=\"glass-card p-5 rounded-xl border-l-4 border-l-secondary\">",
  "<div class=\"flex justify-between items-start mb-4\">",
  "<span class=\"material-symbols-outlined text-secondary\">view_in_ar</span>",
  "<span class=\"px-2 py-1 bg-secondary/10 text-secondary font-label-sm text-label-sm rounded-md\">架构设计</span>",
  "</div>",
  "<h4 class=\"font-headline-md text-headline-md text-on-surface\">微服务迁移方案</h4>",
  "<p class=\"font-body-md text-body-md text-on-surface-variant mt-1 mb-4 line-clamp-2\">核心交易系统的解耦与容器化部署规划。</p>",
  "<div class=\"flex justify-between items-center text-label-sm font-label-sm text-on-surface-variant\">",
  "<span>最后更新: 昨天</span>",
  "<div class=\"flex -space-x-2\">",
  "<div class=\"w-6 h-6 rounded-full bg-surface-container-highest border border-white\"></div>",
  "</div>",
  "</div>",
  "</div>",
  "</div>",
  "</section>",
  "</div>",
  "<!-- Right Column (4 cols) -->",
  "<div class=\"col-span-12 lg:col-span-4 flex flex-col gap-6\">",
  "<!-- Global Activity Feed -->",
  "<section class=\"glass-panel p-6 rounded-2xl flex-1 flex flex-col\">",
  "<h2 class=\"font-headline-md text-headline-md text-on-surface mb-6 flex items-center gap-2\">",
  "<span class=\"material-symbols-outlined\">history</span>",
  "                                    全局活动动态",
  "                                </h2>",
  "<div class=\"relative flex-1\">",
  "<!-- Timeline Line -->",
  "<div class=\"absolute left-[11px] top-2 bottom-0 w-[2px] bg-outline-variant/30\"></div>",
  "<div class=\"flex flex-col gap-6 relative z-10\">",
  "<!-- Feed Item -->",
  "<div class=\"flex gap-4\">",
  "<div class=\"w-6 h-6 rounded-full bg-white border-2 border-primary flex-shrink-0 z-10 mt-1\"></div>",
  "<div>",
  "<p class=\"font-label-md text-label-md text-on-surface\"><span class=\"font-bold\">模型 Alpha</span> 完成了数据集清洗。</p>",
  "<p class=\"font-label-sm text-label-sm text-on-surface-variant mt-1\">10 分钟前</p>",
  "</div>",
  "</div>",
  "<!-- Feed Item -->",
  "<div class=\"flex gap-4\">",
  "<div class=\"w-6 h-6 rounded-full bg-white border-2 border-secondary flex-shrink-0 z-10 mt-1\"></div>",
  "<div>",
  "<p class=\"font-label-md text-label-md text-on-surface\"><span class=\"font-bold\">Alex Chen</span> 部署了新的网络爬虫节点。</p>",
  "<p class=\"font-label-sm text-label-sm text-on-surface-variant mt-1\">1 小时前</p>",
  "</div>",
  "</div>",
  "<!-- Feed Item -->",
  "<div class=\"flex gap-4\">",
  "<div class=\"w-6 h-6 rounded-full bg-white border-2 border-error flex-shrink-0 z-10 mt-1\"></div>",
  "<div>",
  "<p class=\"font-label-md text-label-md text-on-surface\"><span class=\"font-bold\">系统</span> 警告：API 调用速率接近限制。</p>",
  "<p class=\"font-label-sm text-label-sm text-on-surface-variant mt-1\">3 小时前</p>",
  "<div class=\"mt-2 p-3 bg-error-container/50 rounded-lg border border-error/20 font-label-sm text-label-sm text-on-error-container\">",
  "                                                    OpenAI 服务配额使用量已达 85%。",
  "                                                </div>",
  "</div>",
  "</div>",
  "<!-- Feed Item -->",
  "<div class=\"flex gap-4\">",
  "<div class=\"w-6 h-6 rounded-full bg-white border-2 border-outline-variant flex-shrink-0 z-10 mt-1\"></div>",
  "<div>",
  "<p class=\"font-label-md text-label-md text-on-surface\"><span class=\"font-bold\">自动化构建</span> 成功完成。</p>",
  "<p class=\"font-label-sm text-label-sm text-on-surface-variant mt-1\">昨天</p>",
  "</div>",
  "</div>",
  "</div>",
  "</div>",
  "</section>",
  "</div>",
  "</div>",
  "</div>",
  "</main>",
  "</div>",
  "</div>",
  "<!-- Antigravity Particle System Script -->",
  "<script>",
  "        const canvas = document.getElementById('particle-canvas');",
  "        const ctx = canvas.getContext('2d');",
  "",
  "        let particles = [];",
  "",
  "        function resize() {",
  "            canvas.width = canvas.parentElement.clientWidth;",
  "            canvas.height = canvas.parentElement.clientHeight;",
  "        }",
  "",
  "        class Particle {",
  "            constructor() {",
  "                this.x = Math.random() * canvas.width;",
  "                this.y = Math.random() * canvas.height;",
  "                this.size = Math.random() * 4 + 1;",
  "                this.speedY = Math.random() * -0.5 - 0.1; // Float up",
  "                this.speedX = (Math.random() - 0.5) * 0.3; // Slight drift",
  "                this.opacity = Math.random() * 0.5 + 0.1;",
  "            }",
  "",
  "            update() {",
  "                this.y += this.speedY;",
  "                this.x += this.speedX;",
  "",
  "                if (this.y < -10) {",
  "                    this.y = canvas.height + 10;",
  "                    this.x = Math.random() * canvas.width;",
  "                }",
  "            }",
  "",
  "            draw() {",
  "                ctx.fillStyle = 'rgba(0, 120, 212, ' + this.opacity + ')'; // Edge Blue tint",
  "                ctx.beginPath();",
  "                ctx.arc(this.x, this.y, this.size, 0, Math.PI * 2);",
  "                ctx.fill();",
  "            }",
  "        }",
  "",
  "        function init() {",
  "            resize();",
  "            particles = [];",
  "            for (let i = 0; i < 50; i++) {",
  "                particles.push(new Particle());",
  "            }",
  "        }",
  "",
  "        function animate() {",
  "            ctx.clearRect(0, 0, canvas.width, canvas.height);",
  "            particles.forEach(p => {",
  "                p.update();",
  "                p.draw();",
  "            });",
  "            requestAnimationFrame(animate);",
  "        }",
  "",
  "        window.addEventListener('resize', init);",
  "        init();",
  "        animate();",
  "    </script>",
  "</body></html>"
].join("\r\n");

export function WorkbenchPage() {
  return (
    <iframe
      title="Workbench"
      srcDoc={pageHtml}
      sandbox="allow-scripts allow-same-origin allow-popups allow-forms"
      style={{ width: "100%", height: "100vh", border: 0, display: "block" }}
    />
  );
}

export default WorkbenchPage;
