const pageHtml: string = [
  "<!DOCTYPE html>",
  "",
  "<html lang=\"en\"><head>",
  "<meta charset=\"utf-8\"/>",
  "<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\"/>",
  "<title>AetherFlow | Multi-Agent Workspace</title>",
  "<script src=\"https://cdn.tailwindcss.com?plugins=forms,container-queries\"></script>",
  "<link href=\"https://fonts.googleapis.com/css2?family=Hanken+Grotesk:wght@400;500;600;700&amp;display=swap\" rel=\"stylesheet\"/>",
  "<link href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&amp;display=swap\" rel=\"stylesheet\"/>",
  "<style>",
  "        .dewdrop-card {",
  "            background: linear-gradient(135deg, rgba(255, 255, 255, 0.05) 0%, rgba(255, 255, 255, 0.03) 100%);",
  "            backdrop-filter: blur(64px) saturate(150%);",
  "            -webkit-backdrop-filter: blur(64px) saturate(150%);",
  "            border: 1.5px solid transparent;",
  "            background-clip: padding-box;",
  "            box-shadow: ",
  "                0 20px 40px -10px rgba(0, 120, 212, 0.1),",
  "                0 10px 20px -5px rgba(0, 120, 212, 0.05),",
  "                inset 1px 1px 2px rgba(255, 255, 255, 0.4),",
  "                inset -1px -1px 2px rgba(255, 255, 255, 0.05);",
  "            position: relative;",
  "            transition: all 0.4s cubic-bezier(0.23, 1, 0.32, 1);",
  "        }",
  "        ",
  "        .dewdrop-card::after {",
  "            content: '';",
  "            position: absolute;",
  "            inset: 0;",
  "            border-radius: inherit;",
  "            padding: 1px;",
  "            background: linear-gradient(135deg, rgba(255, 255, 255, 0.6) 0%, rgba(255, 255, 255, 0.1) 30%, rgba(255, 255, 255, 0) 100%);",
  "            -webkit-mask: linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0);",
  "            -webkit-mask-composite: xor;",
  "            mask-composite: exclude;",
  "            pointer-events: none;",
  "        }",
  "",
  "        .dewdrop-card::before {",
  "            content: '';",
  "            position: absolute;",
  "            top: 4px;",
  "            left: 4px;",
  "            width: 12px;",
  "            height: 12px;",
  "            border-radius: 50%;",
  "            background: radial-gradient(circle, rgba(255,255,255,0.7) 0%, rgba(255,255,255,0) 70%);",
  "            pointer-events: none;",
  "            z-index: 10;",
  "        }",
  "",
  "        .dewdrop-card:hover {",
  "            transform: translateY(-4px) scale(1.01);",
  "            box-shadow: ",
  "                0 30px 50px -12px rgba(0, 120, 212, 0.15),",
  "                inset 1px 1px 3px rgba(255, 255, 255, 0.5),",
  "                inset -1px -1px 3px rgba(255, 255, 255, 0.1);",
  "            background: linear-gradient(135deg, rgba(255, 255, 255, 0.08) 0%, rgba(255, 255, 255, 0.04) 100%);",
  "        }",
  "",
  "        .dewdrop-panel {",
  "            background: rgba(255, 255, 255, 0.05);",
  "            backdrop-filter: blur(64px) saturate(150%);",
  "            -webkit-backdrop-filter: blur(64px) saturate(150%);",
  "            border: 1px solid rgba(255, 255, 255, 0.1);",
  "            border-top-color: rgba(255, 255, 255, 0.4);",
  "            border-left-color: rgba(255, 255, 255, 0.3);",
  "            box-shadow: ",
  "                0 20px 50px -10px rgba(0, 120, 212, 0.08),",
  "                inset 1px 1px 2px rgba(255, 255, 255, 0.4),",
  "                inset -1px -1px 2px rgba(255, 255, 255, 0.05);",
  "            position: relative;",
  "            overflow: hidden;",
  "        }",
  "",
  "        .dewdrop-panel::before {",
  "            content: '';",
  "            position: absolute;",
  "            top: 0;",
  "            left: 0;",
  "            width: 120px;",
  "            height: 120px;",
  "            background: radial-gradient(circle at 0 0, rgba(255,255,255,0.4) 0%, rgba(255,255,255,0) 70%);",
  "            pointer-events: none;",
  "        }",
  "",
  "        .luminous-button {",
  "            background: #0078d4;",
  "            transition: all 0.3s ease;",
  "            box-shadow: 0 4px 15px rgba(0, 120, 212, 0.4);",
  "        }",
  "        .luminous-button:hover {",
  "            background: #005faa;",
  "            transform: scale(1.02);",
  "            box-shadow: 0 6px 20px rgba(0, 120, 212, 0.6);",
  "        }",
  "        .material-symbols-outlined {",
  "            font-variation-settings: 'FILL' 0, 'wght' 400, 'GRAD' 0, 'opsz' 24;",
  "        }",
  "        ",
  "        /* Custom scrollbar for webkit */",
  "        ::-webkit-scrollbar {",
  "            width: 6px;",
  "            height: 6px;",
  "        }",
  "        ::-webkit-scrollbar-track {",
  "            background: transparent;",
  "        }",
  "        ::-webkit-scrollbar-thumb {",
  "            background: rgba(0, 120, 212, 0.2);",
  "            border-radius: 10px;",
  "        }",
  "        ::-webkit-scrollbar-thumb:hover {",
  "            background: rgba(0, 120, 212, 0.4);",
  "        }",
  "    </style>",
  "<script id=\"tailwind-config\">",
  "        tailwind.config = {",
  "            darkMode: \"class\",",
  "            theme: {",
  "                extend: {",
  "                    \"colors\": {",
  "                        \"on-tertiary-container\": \"#ffffff\",",
  "                        \"surface-tint\": \"#0060ab\",",
  "                        \"outline-variant\": \"#c0c7d4\",",
  "                        \"on-background\": \"#1a1c1c\",",
  "                        \"secondary-fixed\": \"#ecdcff\",",
  "                        \"on-surface-variant\": \"#404752\",",
  "                        \"on-primary-fixed\": \"#001c39\",",
  "                        \"tertiary\": \"#006a5c\",",
  "                        \"surface\": \"#f9f9f9\",",
  "                        \"outline\": \"#717783\",",
  "                        \"on-primary-container\": \"#ffffff\",",
  "                        \"surface-container-high\": \"#e8e8e8\",",
  "                        \"tertiary-fixed\": \"#91f4e1\",",
  "                        \"inverse-primary\": \"#a3c9ff\",",
  "                        \"surface-container\": \"#eeeeee\",",
  "                        \"on-secondary\": \"#ffffff\",",
  "                        \"background\": \"#f9f9f9\",",
  "                        \"secondary-container\": \"#9040ff\",",
  "                        \"on-tertiary\": \"#ffffff\",",
  "                        \"on-primary\": \"#ffffff\",",
  "                        \"on-error-container\": \"#93000a\",",
  "                        \"tertiary-fixed-dim\": \"#75d8c5\",",
  "                        \"on-tertiary-fixed-variant\": \"#005046\",",
  "                        \"surface-bright\": \"#f9f9f9\",",
  "                        \"inverse-on-surface\": \"#f1f1f1\",",
  "                        \"error\": \"#ba1a1a\",",
  "                        \"on-secondary-container\": \"#fdf6ff\",",
  "                        \"secondary-fixed-dim\": \"#d6baff\",",
  "                        \"secondary\": \"#7615e6\",",
  "                        \"inverse-surface\": \"#2f3131\",",
  "                        \"surface-dim\": \"#dadada\",",
  "                        \"surface-container-lowest\": \"#ffffff\",",
  "                        \"on-tertiary-fixed\": \"#00201b\",",
  "                        \"on-primary-fixed-variant\": \"#004883\",",
  "                        \"on-secondary-fixed\": \"#270057\",",
  "                        \"surface-variant\": \"#e2e2e2\",",
  "                        \"tertiary-container\": \"#0a8575\",",
  "                        \"primary-fixed-dim\": \"#a3c9ff\",",
  "                        \"on-surface\": \"#1a1c1c\",",
  "                        \"surface-container-highest\": \"#e2e2e2\",",
  "                        \"primary\": \"#005faa\",",
  "                        \"primary-container\": \"#0078d4\",",
  "                        \"error-container\": \"#ffdad6\",",
  "                        \"on-error\": \"#ffffff\",",
  "                        \"on-secondary-fixed-variant\": \"#5f00c0\",",
  "                        \"surface-container-low\": \"#f3f3f3\",",
  "                        \"primary-fixed\": \"#d3e3ff\"",
  "                    },",
  "                    \"borderRadius\": {",
  "                        \"DEFAULT\": \"0.25rem\",",
  "                        \"lg\": \"0.5rem\",",
  "                        \"xl\": \"0.75rem\",",
  "                        \"full\": \"9999px\"",
  "                    },",
  "                    \"spacing\": {",
  "                        \"max-width\": \"1440px\",",
  "                        \"margin-desktop\": \"48px\",",
  "                        \"margin-mobile\": \"16px\",",
  "                        \"unit\": \"4px\",",
  "                        \"gutter\": \"24px\"",
  "                    },",
  "                    \"fontFamily\": {",
  "                        \"label-md\": [\"Hanken Grotesk\"],",
  "                        \"headline-lg-mobile\": [\"Hanken Grotesk\"],",
  "                        \"headline-lg\": [\"Hanken Grotesk\"],",
  "                        \"headline-md\": [\"Hanken Grotesk\"],",
  "                        \"label-sm\": [\"Hanken Grotesk\"],",
  "                        \"display\": [\"Hanken Grotesk\"],",
  "                        \"body-lg\": [\"Hanken Grotesk\"],",
  "                        \"body-md\": [\"Hanken Grotesk\"]",
  "                    },",
  "                    \"fontSize\": {",
  "                        \"label-md\": [\"14px\", { \"lineHeight\": \"1.4\", \"letterSpacing\": \"0.01em\", \"fontWeight\": \"500\" }],",
  "                        \"headline-lg-mobile\": [\"28px\", { \"lineHeight\": \"1.2\", \"fontWeight\": \"600\" }],",
  "                        \"headline-lg\": [\"32px\", { \"lineHeight\": \"1.2\", \"fontWeight\": \"600\" }],",
  "                        \"headline-md\": [\"24px\", { \"lineHeight\": \"1.3\", \"fontWeight\": \"600\" }],",
  "                        \"label-sm\": [\"12px\", { \"lineHeight\": \"1.4\", \"letterSpacing\": \"0.05em\", \"fontWeight\": \"600\" }],",
  "                        \"display\": [\"56px\", { \"lineHeight\": \"1.1\", \"letterSpacing\": \"-0.02em\", \"fontWeight\": \"700\" }],",
  "                        \"body-lg\": [\"18px\", { \"lineHeight\": \"1.6\", \"fontWeight\": \"400\" }],",
  "                        \"body-md\": [\"16px\", { \"lineHeight\": \"1.5\", \"fontWeight\": \"400\" }]",
  "                    }",
  "                }",
  "            }",
  "        }",
  "    </script>",
  "</head>",
  "<body class=\"bg-surface-container-low text-on-surface font-body-md min-h-screen overflow-hidden selection:bg-primary-container selection:text-on-primary-container flex items-center justify-center bg-gray-200\">",
  "<div class=\"w-[1280px] h-[1024px] bg-surface-container-low text-on-surface font-body-md relative overflow-hidden shadow-2xl flex rounded-xl\">",
  "<!-- Interactive Antigravity Background -->",
  "<canvas class=\"absolute inset-0 z-0 pointer-events-none opacity-60\" id=\"antigravity-canvas\"></canvas>",
  "<!-- Center Content Area (Flexible) -->",
  "<main class=\"relative z-10 flex-1 h-full flex flex-col overflow-hidden px-8\">",
  "<!-- TopNavBar -->",
  "<header class=\"dewdrop-panel rounded-b-[32px] mt-0 flex justify-between items-center px-8 h-20 z-50 shrink-0 mb-6\">",
  "<div class=\"flex items-center gap-6\">",
  "<button class=\"text-on-surface-variant hover:text-primary-container transition-colors flex items-center justify-center p-2 -ml-4 rounded-full hover:bg-white/40\">",
  "<span class=\"material-symbols-outlined text-[24px]\">arrow_back</span>",
  "</button>",
  "<span class=\"font-headline-lg text-headline-lg text-primary-container\">AetherFlow</span>",
  "<div class=\"relative group ml-2\">",
  "<span class=\"absolute inset-y-0 left-3 flex items-center text-on-surface-variant\">",
  "<span class=\"material-symbols-outlined text-[20px]\" data-icon=\"search\">search</span>",
  "</span>",
  "<input class=\"bg-white/50 border border-white/40 rounded-full py-2 pl-10 pr-4 text-body-md text-on-surface focus:outline-none focus:ring-2 focus:ring-primary-container/50 w-64 transition-all duration-300 placeholder:text-on-surface-variant\" placeholder=\"Search Agents...\" type=\"text\"/>",
  "</div>",
  "</div>",
  "<div class=\"flex items-center gap-6\">",
  "<button class=\"text-on-surface-variant hover:text-primary-container transition-colors\">",
  "<span class=\"material-symbols-outlined\" data-icon=\"dark_mode\">dark_mode</span>",
  "</button>",
  "<button class=\"text-on-surface-variant hover:text-primary-container transition-colors\">",
  "<span class=\"material-symbols-outlined\" data-icon=\"notifications\">notifications</span>",
  "</button>",
  "<button class=\"text-on-surface-variant hover:text-primary-container transition-colors\">",
  "<span class=\"material-symbols-outlined\" data-icon=\"settings\">settings</span>",
  "</button>",
  "<div class=\"h-10 w-10 rounded-full border border-primary-container/30 p-0.5\">",
  "<img alt=\"User profile avatar\" class=\"h-full w-full rounded-full object-cover\" src=\"https://lh3.googleusercontent.com/aida-public/AB6AXuA6V-wslhRmShUHyN-xXCJuih56wmU5OHR15g1QdaoveMsTH0DY-hNPep0xFKlaw183ee4xMQwBDiyG0BFnIyrLAccpkKWN7rNsM1tRg1C1rqUstDRYVWuMMqEyt7ivFFoBkl0bEuBBoykg2hxrI33HnjNb5Bq7N-02qTZ3iTvQVdtq3aMe2WPK4SVECp7qLa3UFvZRJZhaNwYgmqIPtT_2yEJ28NePm0abGPgSVaEId3RRJSkPTc3OkxgWAZ-UAv_nlixAvp4YC6_h\"/>",
  "</div>",
  "</div>",
  "</header>",
  "<!-- Page Content -->",
  "<section class=\"flex-1 overflow-y-auto pb-6 relative z-10 px-2\">",
  "<header class=\"mb-8 pt-2\">",
  "<h2 class=\"font-display text-[40px] leading-tight text-on-surface mb-2\">Agent Marketplace</h2>",
  "<p class=\"font-body-lg text-on-surface-variant max-w-2xl\">Orchestrate your workflow with high-performance neural entities. Each agent is specialized for complex multi-step reasoning and execution.</p>",
  "<div class=\"flex gap-3 mt-6\">",
  "<button class=\"px-4 py-1.5 rounded-full bg-primary-container text-on-primary text-label-md\">All Agents</button>",
  "<button class=\"px-4 py-1.5 rounded-full bg-white/40 border border-white/60 text-on-surface text-label-md hover:bg-white/60 transition-colors\">Engineering</button>",
  "<button class=\"px-4 py-1.5 rounded-full bg-white/40 border border-white/60 text-on-surface text-label-md hover:bg-white/60 transition-colors\">Marketing</button>",
  "<button class=\"px-4 py-1.5 rounded-full bg-white/40 border border-white/60 text-on-surface text-label-md hover:bg-white/60 transition-colors\">Design</button>",
  "</div>",
  "</header>",
  "<div class=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6\">",
  "<!-- Agent Card 1 -->",
  "<div class=\"dewdrop-card rounded-2xl p-6 flex flex-col gap-4\">",
  "<div class=\"flex items-center gap-4\">",
  "<div class=\"w-12 h-12 rounded-full bg-primary/20 border border-primary/30 flex items-center justify-center text-primary-container shrink-0\">",
  "<span class=\"material-symbols-outlined text-2xl\">code</span>",
  "</div>",
  "<div>",
  "<h3 class=\"font-headline-md text-xl text-on-surface\">Code Refactor Pro</h3>",
  "<p class=\"text-label-sm text-primary-container uppercase tracking-wider mt-0.5\">Engineering</p>",
  "</div>",
  "</div>",
  "<p class=\"text-body-md text-on-surface-variant flex-1\">Specializes in modernizing legacy codebases, improving performance, and ensuring best practices across your entire stack.</p>",
  "<div class=\"flex flex-wrap gap-2 mt-2\">",
  "<span class=\"px-2.5 py-1 rounded-md bg-secondary-fixed/50 border border-secondary-fixed text-on-secondary-fixed-variant text-label-sm\">React</span>",
  "<span class=\"px-2.5 py-1 rounded-md bg-secondary-fixed/50 border border-secondary-fixed text-on-secondary-fixed-variant text-label-sm\">TypeScript</span>",
  "<span class=\"px-2.5 py-1 rounded-md bg-secondary-fixed/50 border border-secondary-fixed text-on-secondary-fixed-variant text-label-sm\">Node.js</span>",
  "</div>",
  "<button class=\"luminous-button w-full py-2.5 rounded-lg text-on-primary font-label-md mt-4 flex justify-center items-center gap-2\">",
  "<span>Deploy Agent</span>",
  "<span class=\"material-symbols-outlined text-[18px]\">rocket_launch</span>",
  "</button>",
  "</div>",
  "<!-- Agent Card 2 -->",
  "<div class=\"dewdrop-card rounded-2xl p-6 flex flex-col gap-4\">",
  "<div class=\"flex items-center gap-4\">",
  "<div class=\"w-12 h-12 rounded-full bg-tertiary/20 border border-tertiary/30 flex items-center justify-center text-tertiary shrink-0\">",
  "<span class=\"material-symbols-outlined text-2xl\">campaign</span>",
  "</div>",
  "<div>",
  "<h3 class=\"font-headline-md text-xl text-on-surface\">Campaign Architect</h3>",
  "<p class=\"text-label-sm text-tertiary uppercase tracking-wider mt-0.5\">Marketing</p>",
  "</div>",
  "</div>",
  "<p class=\"text-body-md text-on-surface-variant flex-1\">Designs and executes multi-channel marketing campaigns, analyzing engagement metrics to optimize conversion rates in real-time.</p>",
  "<div class=\"flex flex-wrap gap-2 mt-2\">",
  "<span class=\"px-2.5 py-1 rounded-md bg-tertiary-fixed/50 border border-tertiary-fixed text-on-tertiary-fixed-variant text-label-sm\">SEO</span>",
  "<span class=\"px-2.5 py-1 rounded-md bg-tertiary-fixed/50 border border-tertiary-fixed text-on-tertiary-fixed-variant text-label-sm\">Copywriting</span>",
  "<span class=\"px-2.5 py-1 rounded-md bg-tertiary-fixed/50 border border-tertiary-fixed text-on-tertiary-fixed-variant text-label-sm\">Analytics</span>",
  "</div>",
  "<button class=\"luminous-button w-full py-2.5 rounded-lg text-on-primary font-label-md mt-4 flex justify-center items-center gap-2\">",
  "<span>Deploy Agent</span>",
  "<span class=\"material-symbols-outlined text-[18px]\">rocket_launch</span>",
  "</button>",
  "</div>",
  "<!-- Agent Card 3 -->",
  "<div class=\"dewdrop-card rounded-2xl p-6 flex flex-col gap-4\">",
  "<div class=\"flex items-center gap-4\">",
  "<div class=\"w-12 h-12 rounded-full bg-error/20 border border-error/30 flex items-center justify-center text-error shrink-0\">",
  "<span class=\"material-symbols-outlined text-2xl\">bug_report</span>",
  "</div>",
  "<div>",
  "<h3 class=\"font-headline-md text-xl text-on-surface\">QA Automator X</h3>",
  "<p class=\"text-label-sm text-error uppercase tracking-wider mt-0.5\">Engineering</p>",
  "</div>",
  "</div>",
  "<p class=\"text-body-md text-on-surface-variant flex-1\">Automatically generates and runs comprehensive test suites. Detects edge cases, visual regressions, and security vulnerabilities.</p>",
  "<div class=\"flex flex-wrap gap-2 mt-2\">",
  "<span class=\"px-2.5 py-1 rounded-md bg-error-container/50 border border-error-container text-on-error-container text-label-sm\">Cypress</span>",
  "<span class=\"px-2.5 py-1 rounded-md bg-error-container/50 border border-error-container text-on-error-container text-label-sm\">Jest</span>",
  "<span class=\"px-2.5 py-1 rounded-md bg-error-container/50 border border-error-container text-on-error-container text-label-sm\">Playwright</span>",
  "</div>",
  "<button class=\"luminous-button w-full py-2.5 rounded-lg text-on-primary font-label-md mt-4 flex justify-center items-center gap-2\">",
  "<span>Deploy Agent</span>",
  "<span class=\"material-symbols-outlined text-[18px]\">rocket_launch</span>",
  "</button>",
  "</div>",
  "<!-- Agent Card 4 -->",
  "<div class=\"dewdrop-card rounded-2xl p-6 flex flex-col gap-4\">",
  "<div class=\"flex items-center gap-4\">",
  "<div class=\"w-12 h-12 rounded-full bg-secondary/20 border border-secondary/30 flex items-center justify-center text-secondary shrink-0\">",
  "<span class=\"material-symbols-outlined text-2xl\">palette</span>",
  "</div>",
  "<div>",
  "<h3 class=\"font-headline-md text-xl text-on-surface\">UI/UX Visionary</h3>",
  "<p class=\"text-label-sm text-secondary uppercase tracking-wider mt-0.5\">Design</p>",
  "</div>",
  "</div>",
  "<p class=\"text-body-md text-on-surface-variant flex-1\">Translates rough wireframes into polished, accessible user interfaces following your specific design system constraints.</p>",
  "<div class=\"flex flex-wrap gap-2 mt-2\">",
  "<span class=\"px-2.5 py-1 rounded-md bg-primary-fixed/50 border border-primary-fixed text-on-primary-fixed-variant text-label-sm\">Figma</span>",
  "<span class=\"px-2.5 py-1 rounded-md bg-primary-fixed/50 border border-primary-fixed text-on-primary-fixed-variant text-label-sm\">Tailwind</span>",
  "<span class=\"px-2.5 py-1 rounded-md bg-primary-fixed/50 border border-primary-fixed text-on-primary-fixed-variant text-label-sm\">A11y</span>",
  "</div>",
  "<button class=\"luminous-button w-full py-2.5 rounded-lg text-on-primary font-label-md mt-4 flex justify-center items-center gap-2\">",
  "<span>Deploy Agent</span>",
  "<span class=\"material-symbols-outlined text-[18px]\">rocket_launch</span>",
  "</button>",
  "</div>",
  "</div>",
  "</section>",
  "<!-- Footer Info Bar -->",
  "<footer class=\"dewdrop-panel rounded-t-[32px] mt-auto py-4 px-8 flex justify-between items-center z-50 relative shrink-0\">",
  "<div class=\"flex items-center gap-8\">",
  "<div class=\"flex items-center gap-2\">",
  "<span class=\"w-2 h-2 bg-green-500 rounded-full animate-pulse\"></span>",
  "<span class=\"font-label-md text-label-md text-on-surface-variant\">4 Agents Active</span>",
  "</div>",
  "<div class=\"flex items-center gap-2\">",
  "<span class=\"material-symbols-outlined text-[16px] text-primary-container\" data-icon=\"memory\">memory</span>",
  "<span class=\"font-label-md text-label-md text-on-surface-variant\">Latency: 12ms</span>",
  "</div>",
  "</div>",
  "<div class=\"font-label-sm text-label-sm text-on-surface-variant\">",
  "                AetherFlow v4.2.0-Alpha | Managed by Nexus Core",
  "            </div>",
  "</footer>",
  "</main>",
  "</div>",
  "<script>",
  "    // Antigravity Particle System",
  "    const canvas = document.getElementById('antigravity-canvas');",
  "    const ctx = canvas.getContext('2d');",
  "    let width, height;",
  "    let particles = [];",
  "",
  "    function resize() {",
  "        width = canvas.width = window.innerWidth;",
  "        height = canvas.height = window.innerHeight;",
  "    }",
  "",
  "    window.addEventListener('resize', resize);",
  "    resize();",
  "",
  "    class Particle {",
  "        constructor() {",
  "            this.x = Math.random() * width;",
  "            this.y = Math.random() * height;",
  "            this.size = Math.random() * 2 + 0.5;",
  "            // Slower speed as requested",
  "            this.speedX = Math.random() * 0.2 - 0.1;",
  "            this.speedY = Math.random() * -0.3 - 0.1;",
  "            this.opacity = Math.random() * 0.5 + 0.1;",
  "        }",
  "",
  "        update() {",
  "            this.x += this.speedX;",
  "            this.y += this.speedY;",
  "",
  "            if (this.y < 0) {",
  "                this.y = height;",
  "                this.x = Math.random() * width;",
  "            }",
  "            if (this.x < 0) this.x = width;",
  "            if (this.x > width) this.x = 0;",
  "        }",
  "",
  "        draw() {",
  "            ctx.fillStyle = `rgba(0, 120, 212, ${this.opacity})`;",
  "            ctx.beginPath();",
  "            ctx.arc(this.x, this.y, this.size, 0, Math.PI * 2);",
  "            ctx.fill();",
  "        }",
  "    }",
  "",
  "    function init() {",
  "        particles = [];",
  "        for (let i = 0; i < 150; i++) {",
  "            particles.push(new Particle());",
  "        }",
  "    }",
  "",
  "    function animate() {",
  "        ctx.clearRect(0, 0, width, height);",
  "        for (let i = 0; i < particles.length; i++) {",
  "            particles[i].update();",
  "            particles[i].draw();",
  "        }",
  "        requestAnimationFrame(animate);",
  "    }",
  "",
  "    init();",
  "    animate();",
  "</script>",
  "</body></html>"
].join("\n");

export function AgentSquarePage() {
  return (
    <iframe
      title="Agent Square"
      srcDoc={pageHtml}
      sandbox="allow-scripts allow-same-origin allow-popups allow-forms"
      style={{ width: "100%", height: "100vh", border: 0, display: "block" }}
    />
  );
}

export default AgentSquarePage;
