const pageHtml: string = [
  "<!DOCTYPE html>",
  "",
  "<html lang=\"en\" style=\"\"><head>",
  "<meta charset=\"utf-8\"/>",
  "<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\"/>",
  "<title>AetherFlow | Nexus Core - Direct Chats</title>",
  "<script src=\"https://cdn.tailwindcss.com?plugins=forms,container-queries\"></script>",
  "<link href=\"https://fonts.googleapis.com/css2?family=Hanken+Grotesk:wght@400;500;600;700;800&amp;family=JetBrains+Mono:wght@400;500&amp;display=swap\" rel=\"stylesheet\"/>",
  "<link href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&amp;display=swap\" rel=\"stylesheet\"/>",
  "<style>    .dewdrop-card {",
  "        background: linear-gradient(135deg, rgba(255, 255, 255, 0.4) 0%, rgba(255, 255, 255, 0.1) 100%);",
  "        backdrop-filter: blur(80px) saturate(150%);",
  "        -webkit-backdrop-filter: blur(80px) saturate(150%);",
  "        border: 1.5px solid rgba(0, 0, 0, 0.05);",
  "        background-clip: padding-box;",
  "        box-shadow: ",
  "            0 20px 40px -10px rgba(0, 0, 0, 0.1),",
  "            0 10px 20px -5px rgba(0, 0, 0, 0.05),",
  "            inset 1px 1px 3px rgba(255, 255, 255, 0.8),",
  "            inset -1px -1px 3px rgba(0, 0, 0, 0.05);",
  "        position: relative;",
  "        transition: all 0.4s cubic-bezier(0.23, 1, 0.32, 1);",
  "    }",
  "    ",
  "    .dewdrop-card::after {",
  "        content: '';",
  "        position: absolute;",
  "        inset: 0;",
  "        border-radius: inherit;",
  "        padding: 1.5px;",
  "        background: linear-gradient(135deg, rgba(255, 255, 255, 1) 0%, rgba(255, 255, 255, 0.2) 30%, rgba(255, 255, 255, 0) 100%);",
  "        -webkit-mask: linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0);",
  "        -webkit-mask-composite: xor;",
  "        mask-composite: exclude;",
  "        pointer-events: none;",
  "    }",
  "",
  "    .dewdrop-card::before {",
  "        content: '';",
  "        position: absolute;",
  "        top: 6px;",
  "        left: 6px;",
  "        width: 16px;",
  "        height: 16px;",
  "        border-radius: 50%;",
  "        background: radial-gradient(circle, rgba(255,255,255,0.8) 0%, rgba(255,255,255,0) 70%);",
  "        pointer-events: none;",
  "        z-index: 10;",
  "    }",
  "",
  "    .dewdrop-card:hover {",
  "        transform: translateY(-4px) scale(1.01);",
  "        box-shadow: ",
  "            0 30px 50px -12px rgba(0, 0, 0, 0.15),",
  "            inset 1px 1px 4px rgba(255, 255, 255, 1),",
  "            inset -1px -1px 4px rgba(0, 0, 0, 0.05);",
  "        background: linear-gradient(135deg, rgba(255, 255, 255, 0.6) 0%, rgba(255, 255, 255, 0.2) 100%);",
  "    }",
  "",
  "    .dewdrop-panel {",
  "        background: rgba(255, 255, 255, 0.3);",
  "        backdrop-filter: blur(64px) saturate(150%);",
  "        -webkit-backdrop-filter: blur(64px) saturate(150%);",
  "        border: 1.5px solid rgba(0, 0, 0, 0.05);",
  "        border-top-color: rgba(255, 255, 255, 0.8);",
  "        border-left-color: rgba(255, 255, 255, 0.4);",
  "        box-shadow: ",
  "            0 20px 50px -10px rgba(0, 0, 0, 0.1),",
  "            inset 1px 1px 2px rgba(255, 255, 255, 0.5),",
  "            inset -1px -1px 2px rgba(0, 0, 0, 0.02);",
  "        position: relative;",
  "        overflow: hidden;",
  "    }",
  "",
  "    .dewdrop-panel::before {",
  "        content: '';",
  "        position: absolute;",
  "        top: 0;",
  "        left: 0;",
  "        width: 120px;",
  "        height: 120px;",
  "        background: radial-gradient(circle at 0 0, rgba(255,255,255,0.8) 0%, rgba(255,255,255,0) 70%);",
  "        pointer-events: none;",
  "    }",
  "",
  "    .luminous-button {",
  "        background: #0078d4;",
  "        transition: all 0.3s ease;",
  "        box-shadow: 0 4px 15px rgba(0, 120, 212, 0.2);",
  "    }",
  "    .luminous-button:hover {",
  "        background: #005faa;",
  "        transform: scale(1.02);",
  "        box-shadow: 0 6px 20px rgba(0, 120, 212, 0.3);",
  "    }",
  "    .material-symbols-outlined {",
  "        font-variation-settings: 'FILL' 0, 'wght' 400, 'GRAD' 0, 'opsz' 24;",
  "    }",
  "    .custom-scrollbar::-webkit-scrollbar {",
  "        width: 4px;",
  "        height: 4px;",
  "    }",
  "    .custom-scrollbar::-webkit-scrollbar-track {",
  "        background: transparent;",
  "    }",
  "    .custom-scrollbar::-webkit-scrollbar-thumb {",
  "        background: rgba(0, 0, 0, 0.1);",
  "        border-radius: 10px;",
  "    }",
  "    ",
  "    .font-mono {",
  "        font-family: 'JetBrains Mono', monospace;",
  "    }",
  "    ",
  "    .message-tree-line {",
  "        position: absolute;",
  "        left: 24px;",
  "        top: 32px;",
  "        bottom: -16px;",
  "        width: 2px;",
  "        background: rgba(0, 0, 0, 0.05);",
  "        z-index: 0;",
  "    }",
  "    ",
  "    .antigravity-bg {",
  "        position: absolute;",
  "        inset: 0;",
  "        z-index: 0;",
  "        pointer-events: none;",
  "        opacity: 0.6;",
  "        background-image: ",
  "            radial-gradient(circle at 15% 50%, rgba(0, 120, 212, 0.05) 0%, transparent 50%),",
  "            radial-gradient(circle at 85% 30%, rgba(118, 21, 230, 0.05) 0%, transparent 50%);",
  "        animation: float 20s infinite alternate ease-in-out;",
  "    }",
  "    ",
  "    @keyframes float {",
  "        0% { transform: translateY(0) scale(1); }",
  "        100% { transform: translateY(-20px) scale(1.05); }",
  "    }",
  "</style>",
  "<script id=\"tailwind-config\">",
  "  tailwind.config = {",
  "    darkMode: \"class\",",
  "    theme: {",
  "      extend: {",
  "        \"colors\": {",
  "                \"error-container\": \"#ffdad6\",",
  "                \"on-tertiary-fixed-variant\": \"#005046\",",
  "                \"on-error\": \"#ffffff\",",
  "                \"surface-container-high\": \"#e8e8e8\",",
  "                \"secondary\": \"#7615e6\",",
  "                \"on-error-container\": \"#93000a\",",
  "                \"surface-dim\": \"#dadada\",",
  "                \"on-secondary-container\": \"#fdf6ff\",",
  "                \"on-tertiary-fixed\": \"#00201b\",",
  "                \"error\": \"#ba1a1a\",",
  "                \"tertiary-container\": \"#0a8575\",",
  "                \"surface-container-highest\": \"#e2e2e2\",",
  "                \"surface\": \"#f9f9f9\",",
  "                \"outline-variant\": \"#c0c7d4\",",
  "                \"primary-container\": \"#0078d4\",",
  "                \"secondary-fixed-dim\": \"#d6baff\",",
  "                \"tertiary\": \"#006a5c\",",
  "                \"surface-bright\": \"#f9f9f9\",",
  "                \"surface-container-lowest\": \"#ffffff\",",
  "                \"primary\": \"#005faa\",",
  "                \"outline\": \"#717783\",",
  "                \"surface-variant\": \"#e2e2e2\",",
  "                \"on-background\": \"#1a1c1c\",",
  "                \"tertiary-fixed-dim\": \"#75d8c5\",",
  "                \"surface-container\": \"#eeeeee\",",
  "                \"surface-container-low\": \"#f3f3f3\",",
  "                \"on-primary-container\": \"#ffffff\",",
  "                \"tertiary-fixed\": \"#91f4e1\",",
  "                \"on-secondary\": \"#ffffff\",",
  "                \"on-primary-fixed\": \"#001c39\",",
  "                \"background\": \"#f9f9f9\",",
  "                \"primary-fixed\": \"#d3e3ff\",",
  "                \"on-surface-variant\": \"#404752\",",
  "                \"secondary-fixed\": \"#ecdcff\",",
  "                \"inverse-surface\": \"#2f3131\",",
  "                \"inverse-on-surface\": \"#f1f1f1\",",
  "                \"primary-fixed-dim\": \"#a3c9ff\",",
  "                \"on-secondary-fixed\": \"#270057\",",
  "                \"on-tertiary-container\": \"#ffffff\",",
  "                \"on-secondary-fixed-variant\": \"#5f00c0\",",
  "                \"surface-tint\": \"#0060ab\",",
  "                \"on-tertiary\": \"#ffffff\",",
  "                \"inverse-primary\": \"#a3c9ff\",",
  "                \"on-primary-fixed-variant\": \"#004883\",",
  "                \"on-surface\": \"#1a1c1c\",",
  "                \"on-primary\": \"#ffffff\",",
  "                \"secondary-container\": \"#9040ff\"",
  "        },",
  "        \"borderRadius\": {",
  "                \"DEFAULT\": \"0.25rem\",",
  "                \"lg\": \"0.5rem\",",
  "                \"xl\": \"0.75rem\",",
  "                \"full\": \"9999px\"",
  "        },",
  "        \"spacing\": {",
  "                \"margin-desktop\": \"48px\",",
  "                \"unit\": \"4px\",",
  "                \"margin-mobile\": \"16px\",",
  "                \"max-width\": \"1440px\",",
  "                \"gutter\": \"24px\"",
  "        },",
  "        \"fontFamily\": {",
  "                \"label-md\": [",
  "                        \"Hanken Grotesk\"",
  "                ],",
  "                \"headline-lg\": [",
  "                        \"Hanken Grotesk\"",
  "                ],",
  "                \"body-md\": [",
  "                        \"Hanken Grotesk\"",
  "                ],",
  "                \"headline-md\": [",
  "                        \"Hanken Grotesk\"",
  "                ],",
  "                \"display\": [",
  "                        \"Hanken Grotesk\"",
  "                ],",
  "                \"body-lg\": [",
  "                        \"Hanken Grotesk\"",
  "                ],",
  "                \"label-sm\": [",
  "                        \"Hanken Grotesk\"",
  "                ],",
  "                \"headline-lg-mobile\": [",
  "                        \"Hanken Grotesk\"",
  "                ]",
  "        },",
  "        \"fontSize\": {",
  "                \"label-md\": [",
  "                        \"14px\",",
  "                        {",
  "                                \"lineHeight\": \"1.4\",",
  "                                \"letterSpacing\": \"0.01em\",",
  "                                \"fontWeight\": \"500\"",
  "                        }",
  "                ],",
  "                \"headline-lg\": [",
  "                        \"32px\",",
  "                        {",
  "                                \"lineHeight\": \"1.2\",",
  "                                \"fontWeight\": \"600\"",
  "                        }",
  "                ],",
  "                \"body-md\": [",
  "                        \"16px\",",
  "                        {",
  "                                \"lineHeight\": \"1.5\",",
  "                                \"fontWeight\": \"400\"",
  "                        }",
  "                ],",
  "                \"headline-md\": [",
  "                        \"24px\",",
  "                        {",
  "                                \"lineHeight\": \"1.3\",",
  "                                \"fontWeight\": \"600\"",
  "                        }",
  "                ],",
  "                \"display\": [",
  "                        \"56px\",",
  "                        {",
  "                                \"lineHeight\": \"1.1\",",
  "                                \"letterSpacing\": \"-0.02em\",",
  "                                \"fontWeight\": \"700\"",
  "                        }",
  "                ],",
  "                \"body-lg\": [",
  "                        \"18px\",",
  "                        {",
  "                                \"lineHeight\": \"1.6\",",
  "                                \"fontWeight\": \"400\"",
  "                        }",
  "                ],",
  "                \"label-sm\": [",
  "                        \"12px\",",
  "                        {",
  "                                \"lineHeight\": \"1.4\",",
  "                                \"letterSpacing\": \"0.05em\",",
  "                                \"fontWeight\": \"600\"",
  "                        }",
  "                ],",
  "                \"headline-lg-mobile\": [",
  "                        \"28px\",",
  "                        {",
  "                                \"lineHeight\": \"1.2\",",
  "                                \"fontWeight\": \"600\"",
  "                        }",
  "                ]",
  "        }",
  "},",
  "    },",
  "  }",
  "</script>",
  "</head>",
  "<body class=\"text-gray-100 font-body-md min-h-screen overflow-hidden selection:bg-primary-container selection:text-white max-w-[1280px] h-[1024px] mx-auto shadow-2xl relative flex items-center justify-center bg-[#050505] bg-surface\"><div class=\"w-[1280px] h-[1024px] overflow-hidden relative shadow-2xl flex bg-surface\">",
  "<div class=\"antigravity-bg\"></div>",
  "<!-- Left Sidebar -->",
  "<aside class=\"w-[280px] flex-shrink-0 dewdrop-panel h-full flex flex-col z-40 border-r border-white/10 relative\">",
  "<div class=\"p-6\">",
  "<button class=\"flex items-center gap-2 text-gray-400 hover:text-primary transition-colors mb-6 group\">",
  "<span class=\"material-symbols-outlined text-[20px] group-hover:-translate-x-1 transition-transform\" data-icon=\"arrow_back\">arrow_back</span>",
  "<span class=\"font-label-md text-label-md\">Back to Main</span>",
  "</button>",
  "<h1 class=\"font-headline-md text-headline-md text-primary\">Nexus Core</h1>",
  "<p class=\"font-label-sm text-label-sm text-gray-500 mt-2 tracking-widest uppercase\">Multi-Agent Workspace</p>",
  "</div>",
  "<div class=\"flex-1 overflow-y-auto custom-scrollbar px-4 pb-4\">",
  "<!-- Project Tree -->",
  "<div class=\"mb-8\">",
  "<h3 class=\"font-label-sm text-label-sm text-primary mb-3 pl-2 tracking-widest uppercase\">Project Structure</h3>",
  "<div class=\"space-y-1\">",
  "<div class=\"flex items-center gap-2 px-2 py-1.5 rounded-lg hover:bg-white/5 cursor-pointer text-on-surface\">",
  "<span class=\"material-symbols-outlined text-[18px] text-gray-400\" data-icon=\"folder_open\">folder_open</span>",
  "<span class=\"font-label-md text-label-md\">nexus-frontend</span>",
  "</div>",
  "<div class=\"pl-6 space-y-1\">",
  "<div class=\"flex items-center gap-2 px-2 py-1.5 rounded-lg hover:bg-white/5 cursor-pointer text-on-surface-variant\">",
  "<span class=\"material-symbols-outlined text-[18px] text-gray-400\" data-icon=\"folder\">folder</span>",
  "<span class=\"font-label-md text-label-md\">src</span>",
  "</div>",
  "<div class=\"pl-6 space-y-1\">",
  "<div class=\"flex items-center gap-2 px-2 py-1.5 rounded-lg bg-primary/10 text-primary-fixed-dim cursor-pointer\">",
  "<span class=\"material-symbols-outlined text-[18px]\" data-icon=\"javascript\">javascript</span>",
  "<span class=\"font-label-md text-label-md\">App.tsx</span>",
  "</div>",
  "<div class=\"flex items-center gap-2 px-2 py-1.5 rounded-lg hover:bg-white/5 cursor-pointer text-on-surface-variant\">",
  "<span class=\"material-symbols-outlined text-[18px] text-gray-400\" data-icon=\"css\">css</span>",
  "<span class=\"font-label-md text-label-md\">globals.css</span>",
  "</div>",
  "</div>",
  "</div>",
  "</div>",
  "</div>",
  "<!-- Agent List -->",
  "<div>",
  "<h3 class=\"font-label-sm text-label-sm text-primary mb-3 pl-2 tracking-widest uppercase\">Active Agents</h3>",
  "<div class=\"space-y-2\">",
  "<div class=\"flex items-center gap-3 px-3 py-2 rounded-xl bg-primary/10 border border-primary/20 cursor-pointer\">",
  "<div class=\"relative w-8 h-8 rounded-lg overflow-hidden flex-shrink-0\">",
  "<img alt=\"Lyra\" class=\"w-full h-full object-cover\" src=\"https://lh3.googleusercontent.com/aida-public/AB6AXuDNyYB-p2aLgv44Nv8cpvOB0CpPL4UDal8hIDgGdBOZP4Bl8pO02qAPb_P4696BGQWUKuuwsASGNwpUjYSoIuMS8F9QTMJ46flamm_eLSHTefDe8H-Wr5_qpIG8qa0RZVXNwreA0qCucrDBYGh3RpcWXT2vuA29BlZGDjigs9vCcsyO8G1AbnqSYzOMw8PIuuTa1exS9laaKzUiAaW2uYJCt_g3nMNFGfcdzIdRFM9YQ4JVMYack_Ehmyzxd3-UTEubV0ayXdpWhqOj\"/>",
  "<div class=\"absolute bottom-0 right-0 w-2.5 h-2.5 bg-green-500 rounded-full border border-[#050505]\"></div>",
  "</div>",
  "<div class=\"flex-1 min-w-0\">",
  "<div class=\"font-label-md text-label-md text-on-surface truncate\">Lyra Synthesis</div>",
  "<div class=\"font-label-sm text-label-sm text-gray-500 truncate\">Orchestration</div>",
  "</div>",
  "</div>",
  "<div class=\"flex items-center gap-3 px-3 py-2 rounded-xl hover:bg-white/5 cursor-pointer\">",
  "<div class=\"relative w-8 h-8 rounded-lg overflow-hidden flex-shrink-0 dewdrop-card flex items-center justify-center\">",
  "<span class=\"material-symbols-outlined text-secondary\" data-icon=\"code\">code</span>",
  "<div class=\"absolute bottom-0 right-0 w-2.5 h-2.5 bg-gray-500 rounded-full border border-[#050505]\"></div>",
  "</div>",
  "<div class=\"flex-1 min-w-0\">",
  "<div class=\"font-label-md text-label-md text-on-surface-variant truncate\">Coder-Beta</div>",
  "<div class=\"font-label-sm text-label-sm text-gray-500 truncate\">Frontend Dev</div>",
  "</div>",
  "</div>",
  "</div>",
  "</div>",
  "</div>",
  "</aside>",
  "<!-- Center Chat -->",
  "<main class=\"flex-1 flex flex-col relative h-full min-w-0 z-30\">",
  "<header class=\"h-16 flex-shrink-0 dewdrop-panel border-b border-white/10 flex justify-between items-center px-6\">",
  "<div class=\"flex items-center gap-4\">",
  "<h2 class=\"font-headline-md text-headline-md text-on-surface\">Lyra Synthesis Session</h2>",
  "<span class=\"px-2 py-0.5 rounded bg-primary/20 text-primary-fixed-dim text-[10px] font-label-sm uppercase tracking-widest border border-primary/30\">Active</span>",
  "</div>",
  "<div class=\"flex items-center gap-4\">",
  "<div class=\"relative\">",
  "<span class=\"absolute inset-y-0 left-3 flex items-center text-gray-400\">",
  "<span class=\"material-symbols-outlined text-[18px]\" data-icon=\"search\">search</span>",
  "</span>",
  "<input class=\"bg-black/5 border border-black/10 rounded-full py-1.5 pl-9 pr-4 text-label-md text-on-surface focus:outline-none focus:ring-1 focus:ring-primary-container w-48 placeholder:text-gray-500\" placeholder=\"Search chat...\" type=\"text\"/>",
  "</div>",
  "<button class=\"text-gray-400 hover:text-primary-fixed-dim transition-colors\">",
  "<span class=\"material-symbols-outlined\" data-icon=\"more_vert\">more_vert</span>",
  "</button>",
  "</div>",
  "</header>",
  "<div class=\"flex-1 overflow-y-auto p-6 space-y-6 custom-scrollbar\" id=\"chat-container\">",
  "<!-- L0 Request -->",
  "<div class=\"flex gap-4 relative\">",
  "<div class=\"w-10 h-10 rounded-xl bg-primary/10 flex-shrink-0 flex items-center justify-center z-10 border border-primary/20\">",
  "<img alt=\"User\" class=\"w-full h-full rounded-xl object-cover\" src=\"https://lh3.googleusercontent.com/aida-public/AB6AXuAY5OWxam_-ImQmYg80RvYfSDzXNqjODoYxzVnH7UG8AClbfjJXEzkY9-OM9_mP2YOmCyUIFAODkYdWQXN93-Q7K3nCwBivFfdGL6l2NsHmTlqN27GYRrQ2kjLt1S4n1BmtKNjLnn5E3ID8vUatgFyRjcbTllM_bQSMK_eq-4bmnXhSb1vObON1vmesQOjm-LtKKXgMJuQLMOkrnv4FnKqJV8J3IK6SErFkULwFWCY8hiudtzTfrCCklnV6oTUDAC_Zf4o48B7m9sPl\"/>",
  "</div>",
  "<div class=\"flex-1 space-y-2\">",
  "<div class=\"flex items-center gap-2\">",
  "<span class=\"font-label-sm text-[12px] font-bold text-on-surface uppercase tracking-wider\">User</span>",
  "<span class=\"text-gray-500 text-[11px] font-mono\">10:24 AM</span>",
  "</div>",
  "<div class=\"font-body-md text-body-md text-on-surface bg-white/5 p-4 rounded-2xl rounded-tl-sm border border-white/10 max-w-3xl shadow-sm\">",
  "                  Please update the App.tsx to include the new routing structure for the dashboard components we discussed earlier.",
  "                </div>",
  "</div>",
  "</div>",
  "<!-- L1 Agent Thinking -->",
  "<div class=\"flex gap-4 relative ml-8\">",
  "<div class=\"message-tree-line\"></div>",
  "<div class=\"w-8 h-8 rounded-lg dewdrop-card flex-shrink-0 flex items-center justify-center z-10 border border-secondary/20\">",
  "<img alt=\"Lyra\" class=\"w-full h-full rounded-lg object-cover\" src=\"https://lh3.googleusercontent.com/aida-public/AB6AXuDNyYB-p2aLgv44Nv8cpvOB0CpPL4UDal8hIDgGdBOZP4Bl8pO02qAPb_P4696BGQWUKuuwsASGNwpUjYSoIuMS8F9QTMJ46flamm_eLSHTefDe8H-Wr5_qpIG8qa0RZVXNwreA0qCucrDBYGh3RpcWXT2vuA29BlZGDjigs9vCcsyO8G1AbnqSYzOMw8PIuuTa1exS9laaKzUiAaW2uYJCt_g3nMNFGfcdzIdRFM9YQ4JVMYack_Ehmyzxd3-UTEubV0ayXdpWhqOj\"/>",
  "</div>",
  "<div class=\"flex-1 space-y-2\">",
  "<div class=\"flex items-center gap-2\">",
  "<span class=\"font-label-sm text-[12px] font-bold text-primary uppercase tracking-wider\">Lyra Synthesis</span>",
  "<span class=\"text-gray-500 text-[11px] font-mono\">10:24 AM</span>",
  "<span class=\"px-1.5 py-0.5 rounded bg-secondary/10 text-secondary text-[9px] font-bold uppercase tracking-widest ml-2 border border-secondary/20\">Thinking</span>",
  "</div>",
  "<div class=\"font-body-md text-body-md text-gray-400 bg-black/5 p-3 rounded-xl rounded-tl-sm border border-black/10 max-w-2xl text-sm italic\">",
  "                  I need to analyze the current App.tsx file and propose the routing changes. I'll read the file first.",
  "                </div>",
  "</div>",
  "</div>",
  "<!-- L2 Tool Use -->",
  "<div class=\"flex gap-4 relative ml-16\">",
  "<div class=\"message-tree-line\"></div>",
  "<div class=\"w-6 h-6 rounded bg-gray-800 flex-shrink-0 flex items-center justify-center z-10 border border-gray-700\">",
  "<span class=\"material-symbols-outlined text-[14px] text-gray-300\" data-icon=\"terminal\">terminal</span>",
  "</div>",
  "<div class=\"flex-1 space-y-1\">",
  "<div class=\"flex items-center gap-2\">",
  "<span class=\"font-label-sm text-[11px] font-bold text-gray-400 uppercase tracking-wider\">Tool: read_file</span>",
  "<span class=\"text-gray-500 text-[10px] font-mono\">10:25 AM</span>",
  "</div>",
  "<div class=\"font-mono text-[12px] text-gray-300 bg-[#1e1e1e] p-3 rounded-lg border border-gray-700 max-w-2xl overflow-x-auto shadow-inner\">",
  "<div class=\"text-blue-400 mb-1\">$ cat src/App.tsx</div>",
  "<div class=\"text-gray-400\">Loading contents... 45 lines read.</div>",
  "</div>",
  "</div>",
  "</div>",
  "<!-- L1 Agent Response -->",
  "<div class=\"flex gap-4 relative ml-8\">",
  "<div class=\"w-8 h-8 rounded-lg dewdrop-card flex-shrink-0 flex items-center justify-center z-10 border-l-2 border-primary\">",
  "<img alt=\"Lyra\" class=\"w-full h-full rounded-lg object-cover\" src=\"https://lh3.googleusercontent.com/aida-public/AB6AXuDNyYB-p2aLgv44Nv8cpvOB0CpPL4UDal8hIDgGdBOZP4Bl8pO02qAPb_P4696BGQWUKuuwsASGNwpUjYSoIuMS8F9QTMJ46flamm_eLSHTefDe8H-Wr5_qpIG8qa0RZVXNwreA0qCucrDBYGh3RpcWXT2vuA29BlZGDjigs9vCcsyO8G1AbnqSYzOMw8PIuuTa1exS9laaKzUiAaW2uYJCt_g3nMNFGfcdzIdRFM9YQ4JVMYack_Ehmyzxd3-UTEubV0ayXdpWhqOj\"/>",
  "</div>",
  "<div class=\"flex-1 space-y-2\">",
  "<div class=\"flex items-center gap-2\">",
  "<span class=\"font-label-sm text-[12px] font-bold text-primary uppercase tracking-wider\">Lyra Synthesis</span>",
  "<span class=\"text-gray-500 text-[11px] font-mono\">10:25 AM</span>",
  "</div>",
  "<div class=\"font-body-md text-body-md text-on-surface dewdrop-card p-5 rounded-2xl rounded-tl-sm border border-white/10 max-w-3xl shadow-md\">",
  "                  I've reviewed `src/App.tsx`. I will update it to include routes for `/dashboard`, `/dashboard/analytics`, and `/dashboard/settings`. I've prepared the changes.",
  "                </div>",
  "</div>",
  "</div>",
  "</div>",
  "<div class=\"p-6 pt-0 mt-auto bg-surface/80 backdrop-blur-md\">",
  "<div class=\"dewdrop-card rounded-2xl p-2 flex items-end gap-3 transition-all border border-white/20 shadow-lg\">",
  "<button class=\"p-2.5 text-gray-400 hover:text-primary-fixed-dim transition-colors rounded-lg hover:bg-white/5\">",
  "<span class=\"material-symbols-outlined text-[20px]\" data-icon=\"add\">add</span>",
  "</button>",
  "<textarea class=\"flex-1 bg-transparent border-none focus:ring-0 text-body-md font-body-md text-on-surface placeholder:text-gray-500 resize-none py-2.5 min-h-[44px] max-h-[160px]\" placeholder=\"Message Lyra...\" rows=\"1\"></textarea>",
  "<div class=\"flex items-center gap-1.5 p-1\">",
  "<button class=\"p-2 text-gray-400 hover:text-on-surface transition-colors rounded-lg hover:bg-white/5\">",
  "<span class=\"material-symbols-outlined text-[20px]\" data-icon=\"mic\">mic</span>",
  "</button>",
  "<button class=\"luminous-button p-2.5 rounded-xl hover:scale-105 active:scale-95 transition-all text-white flex items-center justify-center\">",
  "<span class=\"material-symbols-outlined text-[18px]\" data-icon=\"send\" data-weight=\"fill\">send</span>",
  "</button>",
  "</div>",
  "</div>",
  "</div>",
  "</main>",
  "<!-- Right Panel -->",
  "<aside class=\"w-[420px] flex-shrink-0 dewdrop-panel h-full flex flex-col z-40 border-l border-white/10 relative\">",
  "<div class=\"flex border-b border-white/10 px-2 pt-2 bg-black/5\">",
  "<button class=\"px-4 py-3 text-label-sm font-label-sm uppercase tracking-wider text-primary border-b-2 border-primary bg-white/5 rounded-t-lg\">Files</button>",
  "<button class=\"px-4 py-3 text-label-sm font-label-sm uppercase tracking-wider text-gray-500 hover:text-on-surface transition-colors\">Diff</button>",
  "<button class=\"px-4 py-3 text-label-sm font-label-sm uppercase tracking-wider text-gray-500 hover:text-on-surface transition-colors\">Preview</button>",
  "<button class=\"px-4 py-3 text-label-sm font-label-sm uppercase tracking-wider text-gray-500 hover:text-on-surface transition-colors\">Git</button>",
  "<button class=\"px-4 py-3 text-label-sm font-label-sm uppercase tracking-wider text-gray-500 hover:text-on-surface transition-colors\">Logs</button>",
  "<button class=\"px-4 py-3 text-label-sm font-label-sm uppercase tracking-wider text-gray-500 hover:text-on-surface transition-colors\">Terminal</button>",
  "</div>",
  "<div class=\"flex-1 overflow-y-auto custom-scrollbar flex flex-col bg-[#1e1e1e]/80 backdrop-blur-md\">",
  "<div class=\"p-3 border-b border-gray-800 flex justify-between items-center bg-[#252526]\">",
  "<span class=\"font-mono text-[12px] text-gray-300\">src/App.tsx</span>",
  "<div class=\"flex gap-2\">",
  "<button class=\"text-gray-400 hover:text-white p-1 rounded hover:bg-white/10\"><span class=\"material-symbols-outlined text-[16px]\" data-icon=\"content_copy\">content_copy</span></button>",
  "<button class=\"text-gray-400 hover:text-white p-1 rounded hover:bg-white/10\"><span class=\"material-symbols-outlined text-[16px]\" data-icon=\"open_in_new\">open_in_new</span></button>",
  "</div>",
  "</div>",
  "<pre class=\"p-4 font-mono text-[13px] leading-relaxed text-gray-300 overflow-x-auto flex-1\"><code class=\"language-tsx\"><span class=\"text-pink-400\">import</span> React <span class=\"text-pink-400\">from</span> <span class=\"text-green-300\">'react'</span>;",
  "<span class=\"text-pink-400\">import</span> { BrowserRouter <span class=\"text-pink-400\">as</span> Router, Routes, Route } <span class=\"text-pink-400\">from</span> <span class=\"text-green-300\">'react-router-dom'</span>;",
  "<span class=\"text-pink-400\">import</span> Dashboard <span class=\"text-pink-400\">from</span> <span class=\"text-green-300\">'./components/Dashboard'</span>;",
  "<span class=\"text-pink-400\">import</span> Analytics <span class=\"text-pink-400\">from</span> <span class=\"text-green-300\">'./components/Analytics'</span>;",
  "<span class=\"text-pink-400\">import</span> Settings <span class=\"text-pink-400\">from</span> <span class=\"text-green-300\">'./components/Settings'</span>;",
  "",
  "<span class=\"text-blue-400\">function</span> <span class=\"text-yellow-200\">App</span>() {",
  "  <span class=\"text-pink-400\">return</span> (",
  "    &lt;<span class=\"text-blue-300\">Router</span>&gt;",
  "      &lt;<span class=\"text-blue-300\">Routes</span>&gt;",
  "        &lt;<span class=\"text-blue-300\">Route</span> <span class=\"text-blue-200\">path</span>=<span class=\"text-green-300\">\"/\"</span> <span class=\"text-blue-200\">element</span>={&lt;<span class=\"text-blue-300\">Dashboard</span> /&gt;} /&gt;",
  "        &lt;<span class=\"text-blue-300\">Route</span> <span class=\"text-blue-200\">path</span>=<span class=\"text-green-300\">\"/dashboard\"</span> <span class=\"text-blue-200\">element</span>={&lt;<span class=\"text-blue-300\">Dashboard</span> /&gt;} /&gt;",
  "        <span class=\"bg-green-900/40 block w-full px-1 border-l-2 border-green-500\">        &lt;<span class=\"text-blue-300\">Route</span> <span class=\"text-blue-200\">path</span>=<span class=\"text-green-300\">\"/dashboard/analytics\"</span> <span class=\"text-blue-200\">element</span>={&lt;<span class=\"text-blue-300\">Analytics</span> /&gt;} /&gt;</span>",
  "        <span class=\"bg-green-900/40 block w-full px-1 border-l-2 border-green-500\">        &lt;<span class=\"text-blue-300\">Route</span> <span class=\"text-blue-200\">path</span>=<span class=\"text-green-300\">\"/dashboard/settings\"</span> <span class=\"text-blue-200\">element</span>={&lt;<span class=\"text-blue-300\">Settings</span> /&gt;} /&gt;</span>",
  "      &lt;/<span class=\"text-blue-300\">Routes</span>&gt;",
  "    &lt;/<span class=\"text-blue-300\">Router</span>&gt;",
  "  );",
  "}",
  "",
  "<span class=\"text-pink-400\">export default</span> App;</code></pre>",
  "</div>",
  "</aside>",
  "</div></body></html>"
].join("\n");

export function PrivateChatsPage() {
  return (
    <iframe
      title="Private Chats"
      srcDoc={pageHtml}
      sandbox="allow-scripts allow-same-origin allow-popups allow-forms"
      style={{ width: "100%", height: "100vh", border: 0, display: "block" }}
    />
  );
}

export default PrivateChatsPage;
