const pageHtml: string = [
  "<!DOCTYPE html>",
  "",
  "<html lang=\"en\"><head>",
  "<meta charset=\"utf-8\"/>",
  "<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\"/>",
  "<title>AetherFlow | Nexus Core Chat</title>",
  "<script src=\"https://cdn.tailwindcss.com?plugins=forms,container-queries\"></script>",
  "<script id=\"tailwind-config\">",
  "    tailwind.config = {",
  "        darkMode: \"class\",",
  "        theme: {",
  "            extend: {",
  "                \"colors\": {",
  "                    \"on-tertiary-container\": \"#ffffff\",",
  "                    \"surface-tint\": \"#0060ab\",",
  "                    \"outline-variant\": \"#c0c7d4\",",
  "                    \"on-background\": \"#1a1c1c\",",
  "                    \"secondary-fixed\": \"#ecdcff\",",
  "                    \"on-surface-variant\": \"#404752\",",
  "                    \"on-primary-fixed\": \"#001c39\",",
  "                    \"tertiary\": \"#006a5c\",",
  "                    \"surface\": \"#f9f9f9\",",
  "                    \"outline\": \"#717783\",",
  "                    \"on-primary-container\": \"#ffffff\",",
  "                    \"surface-container-high\": \"#e8e8e8\",",
  "                    \"tertiary-fixed\": \"#91f4e1\",",
  "                    \"inverse-primary\": \"#a3c9ff\",",
  "                    \"surface-container\": \"#eeeeee\",",
  "                    \"on-secondary\": \"#ffffff\",",
  "                    \"background\": \"#f9f9f9\",",
  "                    \"secondary-container\": \"#9040ff\",",
  "                    \"on-tertiary\": \"#ffffff\",",
  "                    \"on-primary\": \"#ffffff\",",
  "                    \"on-error-container\": \"#93000a\",",
  "                    \"tertiary-fixed-dim\": \"#75d8c5\",",
  "                    \"on-tertiary-fixed-variant\": \"#005046\",",
  "                    \"surface-bright\": \"#f9f9f9\",",
  "                    \"inverse-on-surface\": \"#f1f1f1\",",
  "                    \"error\": \"#ba1a1a\",",
  "                    \"on-secondary-container\": \"#fdf6ff\",",
  "                    \"secondary-fixed-dim\": \"#d6baff\",",
  "                    \"secondary\": \"#7615e6\",",
  "                    \"inverse-surface\": \"#2f3131\",",
  "                    \"surface-dim\": \"#dadada\",",
  "                    \"surface-container-lowest\": \"#ffffff\",",
  "                    \"on-tertiary-fixed\": \"#00201b\",",
  "                    \"on-primary-fixed-variant\": \"#004883\",",
  "                    \"on-secondary-fixed\": \"#270057\",",
  "                    \"surface-variant\": \"#e2e2e2\",",
  "                    \"tertiary-container\": \"#0a8575\",",
  "                    \"primary-fixed-dim\": \"#a3c9ff\",",
  "                    \"on-surface\": \"#1a1c1c\",",
  "                    \"surface-container-highest\": \"#e2e2e2\",",
  "                    \"primary\": \"#005faa\",",
  "                    \"primary-container\": \"#0078d4\",",
  "                    \"error-container\": \"#ffdad6\",",
  "                    \"on-error\": \"#ffffff\",",
  "                    \"on-secondary-fixed-variant\": \"#5f00c0\",",
  "                    \"surface-container-low\": \"#f3f3f3\",",
  "                    \"primary-fixed\": \"#d3e3ff\"",
  "                },",
  "                \"borderRadius\": {",
  "                    \"DEFAULT\": \"0.25rem\",",
  "                    \"lg\": \"0.5rem\",",
  "                    \"xl\": \"0.75rem\",",
  "                    \"full\": \"9999px\"",
  "                },",
  "                \"spacing\": {",
  "                    \"max-width\": \"1440px\",",
  "                    \"margin-desktop\": \"48px\",",
  "                    \"margin-mobile\": \"16px\",",
  "                    \"unit\": \"4px\",",
  "                    \"gutter\": \"24px\",",
  "                    \"stack-sm\": \"8px\",",
  "                    \"stack-md\": \"16px\",",
  "                    \"stack-lg\": \"24px\",",
  "                    \"stack-xl\": \"32px\"",
  "                },",
  "                \"fontFamily\": {",
  "                    \"label-md\": [\"Hanken Grotesk\"],",
  "                    \"headline-lg-mobile\": [\"Hanken Grotesk\"],",
  "                    \"headline-lg\": [\"Hanken Grotesk\"],",
  "                    \"headline-md\": [\"Hanken Grotesk\"],",
  "                    \"label-sm\": [\"Hanken Grotesk\"],",
  "                    \"display\": [\"Hanken Grotesk\"],",
  "                    \"body-lg\": [\"Hanken Grotesk\"],",
  "                    \"body-md\": [\"Hanken Grotesk\"]",
  "                },",
  "                \"fontSize\": {",
  "                    \"label-caps\": [\"12px\", { \"lineHeight\": \"1.4\", \"letterSpacing\": \"0.05em\", \"fontWeight\": \"600\" }],",
  "                    \"display-lg\": [\"24px\", { \"lineHeight\": \"1.2\", \"fontWeight\": \"700\" }],",
  "                    \"body-md\": [\"16px\", { \"lineHeight\": \"1.5\", \"fontWeight\": \"400\" }]",
  "                }",
  "            }",
  "        }",
  "    }",
  "</script>",
  "<link href=\"https://fonts.googleapis.com/css2?family=Hanken+Grotesk:wght@400;500;600;700;800&amp;display=swap\" rel=\"stylesheet\"/>",
  "<link href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&amp;display=swap\" rel=\"stylesheet\"/>",
  "<style>",
  "    body {",
  "        background-color: #f3f3f3; /* surface-container-low */",
  "        overflow: hidden;",
  "        font-family: 'Hanken Grotesk', sans-serif;",
  "    }",
  "",
  "    .dewdrop-card {",
  "        background: linear-gradient(135deg, rgba(255, 255, 255, 0.15) 0%, rgba(255, 255, 255, 0.05) 100%);",
  "        backdrop-filter: blur(64px) saturate(150%);",
  "        -webkit-backdrop-filter: blur(64px) saturate(150%);",
  "        border: 1.5px solid transparent;",
  "        background-clip: padding-box;",
  "        box-shadow: ",
  "            0 20px 40px -10px rgba(0, 120, 212, 0.15),",
  "            0 10px 20px -5px rgba(0, 120, 212, 0.1),",
  "            inset 2px 2px 4px rgba(255, 255, 255, 0.6),",
  "            inset -2px -2px 4px rgba(255, 255, 255, 0.1);",
  "        position: relative;",
  "        transition: all 0.4s cubic-bezier(0.23, 1, 0.32, 1);",
  "    }",
  "    ",
  "    .dewdrop-card::after {",
  "        content: '';",
  "        position: absolute;",
  "        inset: 0;",
  "        border-radius: inherit;",
  "        padding: 1.5px;",
  "        background: linear-gradient(135deg, rgba(255, 255, 255, 0.9) 0%, rgba(255, 255, 255, 0.2) 30%, rgba(255, 255, 255, 0) 100%);",
  "        -webkit-mask: linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0);",
  "        -webkit-mask-composite: xor;",
  "        mask-composite: exclude;",
  "        pointer-events: none;",
  "    }",
  "",
  "    .dewdrop-card::before {",
  "        content: '';",
  "        position: absolute;",
  "        top: 6px;",
  "        left: 6px;",
  "        width: 16px;",
  "        height: 16px;",
  "        border-radius: 50%;",
  "        background: radial-gradient(circle, rgba(255,255,255,0.9) 0%, rgba(255,255,255,0) 70%);",
  "        pointer-events: none;",
  "        z-index: 10;",
  "    }",
  "",
  "    .dewdrop-card:hover {",
  "        transform: translateY(-4px) scale(1.01);",
  "        box-shadow: ",
  "            0 30px 50px -12px rgba(0, 120, 212, 0.2),",
  "            inset 2px 2px 5px rgba(255, 255, 255, 0.8),",
  "            inset -2px -2px 5px rgba(255, 255, 255, 0.2);",
  "        background: linear-gradient(135deg, rgba(255, 255, 255, 0.25) 0%, rgba(255, 255, 255, 0.1) 100%);",
  "    }",
  "",
  "    .dewdrop-panel {",
  "        background: rgba(255, 255, 255, 0.1);",
  "        backdrop-filter: blur(64px) saturate(150%);",
  "        -webkit-backdrop-filter: blur(64px) saturate(150%);",
  "        border: 1.5px solid rgba(255, 255, 255, 0.1);",
  "        border-top-color: rgba(255, 255, 255, 0.8);",
  "        border-left-color: rgba(255, 255, 255, 0.6);",
  "        box-shadow: ",
  "            0 20px 50px -10px rgba(0, 120, 212, 0.12),",
  "            inset 1px 1px 2px rgba(255, 255, 255, 0.7),",
  "            inset -1px -1px 2px rgba(255, 255, 255, 0.1);",
  "        position: relative;",
  "        overflow: hidden;",
  "    }",
  "",
  "    .dewdrop-panel::before {",
  "        content: '';",
  "        position: absolute;",
  "        top: 0;",
  "        left: 0;",
  "        width: 120px;",
  "        height: 120px;",
  "        background: radial-gradient(circle at 0 0, rgba(255,255,255,0.7) 0%, rgba(255,255,255,0) 70%);",
  "        pointer-events: none;",
  "    }",
  "",
  "    .user-bubble {",
  "        background-color: #0078d4; /* primary-container */",
  "        color: #ffffff;",
  "        border: none;",
  "        box-shadow: 0 4px 15px rgba(0, 120, 212, 0.2);",
  "    }",
  "    ",
  "    .luminous-button {",
  "        background: #0078d4;",
  "        transition: all 0.3s ease;",
  "        box-shadow: 0 4px 15px rgba(0, 120, 212, 0.4);",
  "    }",
  "    .luminous-button:hover {",
  "        background: #005faa;",
  "        transform: scale(1.02);",
  "        box-shadow: 0 6px 20px rgba(0, 120, 212, 0.6);",
  "    }",
  "",
  "    .agent-chip-cyan { border-left: 4px solid #005faa; }",
  "    .agent-chip-violet { border-left: 4px solid #7615e6; }",
  "    .agent-chip-teal { border-left: 4px solid #0a8575; }",
  "",
  "    .custom-scrollbar::-webkit-scrollbar {",
  "        width: 4px;",
  "    }",
  "    .custom-scrollbar::-webkit-scrollbar-track {",
  "        background: transparent;",
  "    }",
  "    .custom-scrollbar::-webkit-scrollbar-thumb {",
  "        background: rgba(0, 0, 0, 0.1);",
  "        border-radius: 10px;",
  "    }",
  "    .material-symbols-outlined {",
  "        font-variation-settings: 'FILL' 0, 'wght' 400, 'GRAD' 0, 'opsz' 24;",
  "    }",
  "    ",
  "    /* Antigravity particles */",
  "    .particles-container {",
  "        position: absolute;",
  "        inset: 0;",
  "        overflow: hidden;",
  "        z-index: 0;",
  "        pointer-events: none;",
  "    }",
  "    .particle {",
  "        position: absolute;",
  "        background: radial-gradient(circle, rgba(0, 120, 212, 0.15) 0%, rgba(0, 120, 212, 0) 70%);",
  "        border-radius: 50%;",
  "        animation: float-up infinite linear;",
  "    }",
  "    @keyframes float-up {",
  "        0% { transform: translateY(100vh) scale(0.5); opacity: 0; }",
  "        50% { opacity: 1; }",
  "        100% { transform: translateY(-20vh) scale(1.5); opacity: 0; }",
  "    }",
  "</style>",
  "</head>",
  "<body class=\"bg-surface-container-low flex items-center justify-center min-h-screen\">",
  "<div class=\"particles-container\">",
  "<div class=\"particle\" style=\"width: 100px; height: 100px; left: 10%; animation-duration: 25s; animation-delay: 0s;\"></div>",
  "<div class=\"particle\" style=\"width: 150px; height: 150px; left: 30%; animation-duration: 35s; animation-delay: -5s;\"></div>",
  "<div class=\"particle\" style=\"width: 80px; height: 80px; left: 60%; animation-duration: 20s; animation-delay: -10s;\"></div>",
  "<div class=\"particle\" style=\"width: 200px; height: 200px; left: 80%; animation-duration: 40s; animation-delay: -15s;\"></div>",
  "<div class=\"particle\" style=\"width: 120px; height: 120px; left: 40%; animation-duration: 30s; animation-delay: -20s;\"></div>",
  "</div>",
  "<div class=\"w-[1280px] h-[1024px] bg-surface-container-low/50 relative overflow-hidden shadow-2xl flex flex-col z-10\">",
  "<aside class=\"dewdrop-panel rounded-r-[32px] absolute left-0 top-0 h-full flex flex-col p-6 z-40 w-64 mix-blend-normal border-r border-white/20\">",
  "<div class=\"mb-10 mt-2\">",
  "<a class=\"flex items-center gap-2 text-on-surface-variant hover:text-primary-container transition-colors font-label-caps text-label-caps mb-8 cursor-pointer\" href=\"#\">",
  "<span class=\"material-symbols-outlined text-[18px]\" data-icon=\"arrow_back\">arrow_back</span>",
  "Dashboard",
  "</a>",
  "<h1 class=\"font-display-lg text-display-lg text-primary-container\">Data Sync</h1>",
  "<p class=\"font-label-caps text-label-caps text-on-surface-variant mt-2 tracking-widest uppercase\">Workspace</p>",
  "</div>",
  "<nav class=\"flex-1 space-y-8\">",
  "<div>",
  "<h3 class=\"font-label-caps text-label-caps text-on-surface-variant mb-3 uppercase tracking-widest\">Project Context</h3>",
  "<div class=\"space-y-2\">",
  "<a class=\"flex items-center gap-3 px-4 py-2.5 rounded-xl transition-all duration-200 ease-in-out bg-primary/10 text-primary-container border-l-2 border-primary-container cursor-pointer\" href=\"#\">",
  "<span class=\"material-symbols-outlined text-[18px]\" data-icon=\"description\">description</span>",
  "<span class=\"font-label-caps text-label-caps\">Legacy Migration</span>",
  "</a>",
  "<a class=\"flex items-center gap-3 px-4 py-2.5 rounded-xl transition-colors duration-200 ease-in-out text-on-surface-variant hover:bg-black/5 hover:text-on-surface cursor-pointer\" href=\"#\">",
  "<span class=\"material-symbols-outlined text-[18px]\" data-icon=\"rule\">rule</span>",
  "<span class=\"font-label-caps text-label-caps\">Mapping Rules</span>",
  "</a>",
  "</div>",
  "</div>",
  "<div>",
  "<h3 class=\"font-label-caps text-label-caps text-on-surface-variant mb-3 uppercase tracking-widest\">Agent Participants</h3>",
  "<div class=\"space-y-2\">",
  "<div class=\"flex items-center gap-3 px-4 py-2 rounded-xl\">",
  "<div class=\"w-2 h-2 rounded-full bg-primary-container\"></div>",
  "<span class=\"font-label-caps text-label-caps text-on-surface\">DataAgent Alpha</span>",
  "</div>",
  "<div class=\"flex items-center gap-3 px-4 py-2 rounded-xl\">",
  "<div class=\"w-2 h-2 rounded-full bg-secondary animate-pulse\"></div>",
  "<span class=\"font-label-caps text-label-caps text-on-surface\">CodeSmith</span>",
  "</div>",
  "<div class=\"flex items-center gap-3 px-4 py-2 rounded-xl\">",
  "<div class=\"w-2 h-2 rounded-full bg-tertiary-container\"></div>",
  "<span class=\"font-label-caps text-label-caps text-on-surface\">Security-Core</span>",
  "</div>",
  "</div>",
  "</div>",
  "</nav>",
  "<div class=\"mt-auto space-y-2 pt-6 border-t border-white/40\">",
  "<a class=\"flex items-center gap-3 px-4 py-3 text-on-surface-variant hover:bg-black/5 cursor-pointer rounded-xl\" href=\"#\">",
  "<span class=\"material-symbols-outlined\" data-icon=\"description\">description</span>",
  "<span class=\"font-label-caps text-label-caps\">Docs</span>",
  "</a>",
  "<a class=\"flex items-center gap-3 px-4 py-3 text-on-surface-variant hover:bg-black/5 cursor-pointer rounded-xl\" href=\"#\">",
  "<span class=\"material-symbols-outlined\" data-icon=\"help\">help</span>",
  "<span class=\"font-label-caps text-label-caps\">Help</span>",
  "</a>",
  "</div>",
  "</aside>",
  "<main class=\"ml-64 flex flex-col h-full overflow-hidden relative z-10\">",
  "<header class=\"dewdrop-panel rounded-b-[32px] mx-6 mt-4 flex justify-between items-center px-10 h-20 z-50 shrink-0 mix-blend-normal\">",
  "<div class=\"flex items-center gap-8\">",
  "<span class=\"font-display-lg text-display-lg text-primary-container\">AetherFlow</span>",
  "<div class=\"relative group hidden lg:block\">",
  "<span class=\"absolute inset-y-0 left-3 flex items-center text-on-surface-variant\">",
  "<span class=\"material-symbols-outlined text-sm\" data-icon=\"search\">search</span>",
  "</span>",
  "<input class=\"bg-white/50 border border-white/40 rounded-full py-2 pl-10 pr-4 text-body-md font-body-md focus:outline-none focus:ring-2 focus:ring-primary-container/50 w-64 text-on-surface placeholder:text-on-surface-variant transition-all duration-300\" placeholder=\"Search interactions...\" type=\"text\"/>",
  "</div>",
  "</div>",
  "<div class=\"flex items-center gap-6\">",
  "<div class=\"flex gap-2\">",
  "<button class=\"text-on-surface-variant hover:text-primary-container transition-colors p-2 rounded-full hover:bg-white/20\">",
  "<span class=\"material-symbols-outlined\" data-icon=\"notifications\">notifications</span>",
  "</button>",
  "<button class=\"text-on-surface-variant hover:text-primary-container transition-colors p-2 rounded-full hover:bg-white/20\">",
  "<span class=\"material-symbols-outlined\" data-icon=\"settings\">settings</span>",
  "</button>",
  "</div>",
  "<div class=\"h-10 w-10 rounded-full border border-primary-container/30 p-0.5\">",
  "<img alt=\"User profile avatar\" class=\"h-full w-full rounded-full object-cover\" src=\"https://lh3.googleusercontent.com/aida-public/AB6AXuDTeH4B0RZkTnjwt4EZYasnHKlEKdyQwm2ULQMC4svgQxu_5qk5CN9WIvYet0yscp9Jf7vkHKFvL9P8p_aHiwX9Ew-_v-m4Z13y2YIbunSYp3rh11mRKVSq2gvSaR_iuuj-4Nw3PGYYmec366lOiQv7Fhn70koEWL1uABR385pkJtjGqvllYIjHkKvITebodVdErjXBl8ML7VH8V2HrldXe86UqszPWKW8Re_D-AtG-LBMTRlpXmEfZzOwOt6D1OnJRJ0mXtF-Tji1-\"/>",
  "</div>",
  "</div>",
  "</header>",
  "<section class=\"flex flex-1 overflow-hidden relative p-6 pt-4 gap-6\">",
  "<div class=\"flex-1 flex flex-col relative overflow-hidden\">",
  "<div class=\"flex-1 overflow-y-auto pr-4 custom-scrollbar space-y-stack-lg pb-4\">",
  "<div class=\"flex justify-center my-stack-lg\">",
  "<span class=\"dewdrop-card px-6 py-2 rounded-full text-xs font-label-caps text-on-surface-variant uppercase tracking-widest\">Task Initiated: Cross-System Data Synchronization</span>",
  "</div>",
  "<!-- Agent Interaction Flow -->",
  "<div class=\"flex gap-stack-md max-w-3xl\">",
  "<img alt=\"DataAgent Alpha\" class=\"w-10 h-10 rounded-full border border-primary/20 mt-6 shrink-0\" src=\"https://lh3.googleusercontent.com/aida-public/AB6AXuC0hoKb87qpZX_LrHuGrfAYKlQhCNztPk-82pCU5vfhXoRxp3onuB4iEiIhBNUPVd-IYkfryYjhmNZosROMUk3emLka3w-BWdHp1qVgNOndgCHHZWYE_qexSuYR3EF9GUvd40wfCPYZPB3gZH1WVEUjjo4fbYodSm_kunbvhyqAv69TFji-sF_n44ydIL_q93QuFy9LGrV3jejFdkHMBddaSxAVrmYrGWKlsGNVaYy5Y7yL09VaT8a1vnEEyD1ElcqBc81xeVci01AE\"/>",
  "<div class=\"flex flex-col gap-1 w-full\">",
  "<span class=\"font-label-caps text-label-caps text-primary-container ml-2\">DataAgent Alpha</span>",
  "<div class=\"dewdrop-card p-6 rounded-[32px] rounded-tl-none agent-chip-cyan\">",
  "<p class=\"text-body-md font-body-md text-on-surface\">I've extracted the core schemas from the legacy database. However, there are several unstructured fields that need mapping. @CodeSmith, can you generate a parsing script for these JSON blobs?</p>",
  "</div>",
  "<span class=\"text-[10px] text-on-surface-variant mt-1 ml-2\">10:42 AM</span>",
  "</div>",
  "</div>",
  "<div class=\"flex gap-stack-md max-w-3xl\">",
  "<img alt=\"CodeSmith\" class=\"w-10 h-10 rounded-full border border-secondary/20 mt-6 shrink-0\" src=\"https://lh3.googleusercontent.com/aida-public/AB6AXuBmY1YtYaBEuAYfsBPi1cOUw05uKxIWtMT3iL6FxImFctFftPUk6yuu762egMrPt__U0UIlCuM-BmVkf1orTy-YNDTK7cIL4Nqumh-6_DOgzNmb-htDEetEKdrU2wJX8CJzhgYhZRqBi7IUPrR1qSIOl_VMXkp-o2M4Hu54CGMeCfN9Tra2yHDCCG7qJGsUgANtl8aW83e-sXHSwrQp2DPcc1XAgpBnCzxbvWuowZrYQ5-VInhmNPeCL5FyEa_oZaX9aTAVyhKgxsyk\"/>",
  "<div class=\"flex flex-col gap-1 w-full\">",
  "<span class=\"font-label-caps text-label-caps text-secondary ml-2\">CodeSmith</span>",
  "<div class=\"dewdrop-card p-6 rounded-[32px] rounded-tl-none agent-chip-violet\">",
  "<p class=\"text-body-md font-body-md text-on-surface\">On it. Analyzing the schema structure...</p>",
  "<div class=\"mt-4 p-4 bg-black/5 rounded-2xl border border-black/5\">",
  "<div class=\"flex justify-between items-center mb-2\">",
  "<span class=\"text-[10px] uppercase font-bold text-secondary flex items-center gap-1\">",
  "<span class=\"material-symbols-outlined text-[14px]\">code</span> Generating Python Parser",
  "                    </span>",
  "<span class=\"text-[10px] text-on-surface-variant\">In Progress</span>",
  "</div>",
  "<div class=\"h-1.5 bg-black/10 rounded-full overflow-hidden\">",
  "<div class=\"h-full bg-secondary w-[45%] rounded-full animate-pulse\"></div>",
  "</div>",
  "</div>",
  "</div>",
  "<span class=\"text-[10px] text-on-surface-variant mt-1 ml-2\">10:43 AM</span>",
  "</div>",
  "</div>",
  "<div class=\"flex gap-stack-md max-w-3xl ml-auto flex-row-reverse\">",
  "<div class=\"w-10 h-10 rounded-full border border-tertiary-container/20 bg-tertiary-container/10 flex items-center justify-center mt-6 shrink-0\">",
  "<span class=\"material-symbols-outlined text-tertiary-container\" data-icon=\"policy\" style=\"font-variation-settings: 'FILL' 1;\">policy</span>",
  "</div>",
  "<div class=\"flex flex-col items-end gap-1 w-full\">",
  "<span class=\"font-label-caps text-label-caps text-tertiary-container mr-2\">Security-Core</span>",
  "<div class=\"dewdrop-card p-6 rounded-[32px] rounded-tr-none agent-chip-teal text-right bg-tertiary-container/5\">",
  "<p class=\"text-body-md font-body-md text-on-surface\">Warning: Detected PII in the unstructured fields. Ensure the parsing script includes data masking for fields: `user_email`, `phone_ext` before synchronization.</p>",
  "</div>",
  "<span class=\"text-[10px] text-on-surface-variant mt-1 mr-2\">10:44 AM • Security Override</span>",
  "</div>",
  "</div>",
  "<div class=\"flex gap-stack-md max-w-3xl\">",
  "<img alt=\"CodeSmith\" class=\"w-10 h-10 rounded-full border border-secondary/20 mt-6 shrink-0\" src=\"https://lh3.googleusercontent.com/aida-public/AB6AXuBmY1YtYaBEuAYfsBPi1cOUw05uKxIWtMT3iL6FxImFctFftPUk6yuu762egMrPt__U0UIlCuM-BmVkf1orTy-YNDTK7cIL4Nqumh-6_DOgzNmb-htDEetEKdrU2wJX8CJzhgYhZRqBi7IUPrR1qSIOl_VMXkp-o2M4Hu54CGMeCfN9Tra2yHDCCG7qJGsUgANtl8aW83e-sXHSwrQp2DPcc1XAgpBnCzxbvWuowZrYQ5-VInhmNPeCL5FyEa_oZaX9aTAVyhKgxsyk\"/>",
  "<div class=\"flex flex-col gap-1 w-full\">",
  "<span class=\"font-label-caps text-label-caps text-secondary ml-2\">CodeSmith</span>",
  "<div class=\"dewdrop-card p-6 rounded-[32px] rounded-tl-none agent-chip-violet\">",
  "<p class=\"text-body-md font-body-md text-on-surface\">Acknowledged @Security-Core. Script updated with RegEx masking. Executing test run against staging environment.</p>",
  "</div>",
  "<span class=\"text-[10px] text-on-surface-variant mt-1 ml-2\">10:45 AM</span>",
  "</div>",
  "</div>",
  "</div>",
  "<!-- Input Area -->",
  "<div class=\"mt-4 relative shrink-0\">",
  "<div class=\"dewdrop-card rounded-[32px] p-6 flex flex-col gap-4\">",
  "<div class=\"flex items-center gap-2 px-2 border-b border-white/20 pb-4\">",
  "<button class=\"p-1.5 rounded-lg hover:bg-black/5 text-on-surface-variant hover:text-primary-container transition-colors\">",
  "<span class=\"material-symbols-outlined text-[20px]\" data-icon=\"alternate_email\">alternate_email</span>",
  "</button>",
  "<button class=\"p-1.5 rounded-lg hover:bg-black/5 text-on-surface-variant hover:text-primary-container transition-colors\">",
  "<span class=\"material-symbols-outlined text-[20px]\" data-icon=\"attachment\">attachment</span>",
  "</button>",
  "<button class=\"p-1.5 rounded-lg hover:bg-black/5 text-on-surface-variant hover:text-primary-container transition-colors\">",
  "<span class=\"material-symbols-outlined text-[20px]\" data-icon=\"code\">code</span>",
  "</button>",
  "<div class=\"h-5 w-px bg-white/40 mx-2\"></div>",
  "<div class=\"flex gap-2 flex-wrap\">",
  "<span class=\"bg-primary/10 text-primary-container px-3 py-1 rounded-full text-xs font-bold\">@DataAgent Alpha</span>",
  "<span class=\"bg-secondary/10 text-secondary px-3 py-1 rounded-full text-xs font-bold\">@CodeSmith</span>",
  "<span class=\"bg-tertiary-container/10 text-tertiary-container px-3 py-1 rounded-full text-xs font-bold\">@Security-Core</span>",
  "</div>",
  "</div>",
  "<div class=\"flex items-end gap-6 px-2\">",
  "<textarea class=\"flex-1 bg-transparent border-none focus:ring-0 text-body-md font-body-md resize-none custom-scrollbar placeholder:text-on-surface-variant text-on-surface py-2\" placeholder=\"Send instruction or context to the agent group...\" rows=\"2\"></textarea>",
  "<button class=\"luminous-button px-8 py-3 rounded-2xl text-on-primary font-bold text-body-md flex items-center gap-2 active:scale-95 mb-1\">",
  "<span class=\"\">Coordinate</span>",
  "<span class=\"material-symbols-outlined\" data-icon=\"group_work\" style=\"font-variation-settings: 'FILL' 1;\">group_work</span>",
  "</button>",
  "</div>",
  "</div>",
  "</div>",
  "</div>",
  "<!-- Right Sidebar -->",
  "<aside class=\"w-80 dewdrop-panel rounded-[32px] flex flex-col p-6 gap-6 mix-blend-normal shrink-0 border-l border-white/20\">",
  "<div>",
  "<h3 class=\"font-label-caps text-label-caps text-on-surface-variant mb-6 flex items-center gap-2 uppercase tracking-widest\">",
  "<span class=\"w-2 h-2 bg-primary-container rounded-full animate-pulse\"></span>Active Agents (3)",
  "          </h3>",
  "<div class=\"space-y-4\">",
  "<div class=\"dewdrop-card p-4 rounded-2xl flex items-center gap-4 cursor-pointer\">",
  "<img alt=\"DataAgent Alpha\" class=\"w-12 h-12 rounded-full object-cover border-2 border-primary-container/30 shrink-0\" src=\"https://lh3.googleusercontent.com/aida-public/AB6AXuC0hoKb87qpZX_LrHuGrfAYKlQhCNztPk-82pCU5vfhXoRxp3onuB4iEiIhBNUPVd-IYkfryYjhmNZosROMUk3emLka3w-BWdHp1qVgNOndgCHHZWYE_qexSuYR3EF9GUvd40wfCPYZPB3gZH1WVEUjjo4fbYodSm_kunbvhyqAv69TFji-sF_n44ydIL_q93QuFy9LGrV3jejFdkHMBddaSxAVrmYrGWKlsGNVaYy5Y7yL09VaT8a1vnEEyD1ElcqBc81xeVci01AE\"/>",
  "<div class=\"flex-1 min-w-0\">",
  "<div class=\"flex justify-between items-center mb-1\">",
  "<span class=\"text-body-md font-bold text-primary-container truncate\">DataAgent Alpha</span>",
  "<span class=\"text-[10px] text-green-600 font-bold tracking-wider shrink-0\">IDLE</span>",
  "</div>",
  "<p class=\"text-xs text-on-surface-variant truncate\">Schema Extraction</p>",
  "</div>",
  "</div>",
  "<div class=\"dewdrop-card p-4 rounded-2xl flex items-center gap-4 cursor-pointer\">",
  "<img alt=\"CodeSmith\" class=\"w-12 h-12 rounded-full object-cover border-2 border-secondary/30 shrink-0\" src=\"https://lh3.googleusercontent.com/aida-public/AB6AXuBmY1YtYaBEuAYfsBPi1cOUw05uKxIWtMT3iL6FxImFctFftPUk6yuu762egMrPt__U0UIlCuM-BmVkf1orTy-YNDTK7cIL4Nqumh-6_DOgzNmb-htDEetEKdrU2wJX8CJzhgYhZRqBi7IUPrR1qSIOl_VMXkp-o2M4Hu54CGMeCfN9Tra2yHDCCG7qJGsUgANtl8aW83e-sXHSwrQp2DPcc1XAgpBnCzxbvWuowZrYQ5-VInhmNPeCL5FyEa_oZaX9aTAVyhKgxsyk\"/>",
  "<div class=\"flex-1 min-w-0\">",
  "<div class=\"flex justify-between items-center mb-1\">",
  "<span class=\"text-body-md font-bold text-secondary truncate\">CodeSmith</span>",
  "<span class=\"text-[10px] text-secondary font-bold tracking-wider animate-pulse shrink-0\">BUSY</span>",
  "</div>",
  "<p class=\"text-xs text-on-surface-variant truncate\">Testing Script...</p>",
  "</div>",
  "</div>",
  "<div class=\"dewdrop-card p-4 rounded-2xl flex items-center gap-4 cursor-pointer\">",
  "<div class=\"w-12 h-12 rounded-full bg-tertiary-container/10 border-2 border-tertiary-container/30 flex items-center justify-center shrink-0\">",
  "<span class=\"material-symbols-outlined text-tertiary-container\" data-icon=\"policy\">policy</span>",
  "</div>",
  "<div class=\"flex-1 min-w-0\">",
  "<div class=\"flex justify-between items-center mb-1\">",
  "<span class=\"text-body-md font-bold text-tertiary-container truncate\">Security-Core</span>",
  "<span class=\"text-[10px] text-green-600 font-bold tracking-wider shrink-0\">READY</span>",
  "</div>",
  "<p class=\"text-xs text-on-surface-variant truncate\">Compliance Monitoring</p>",
  "</div>",
  "</div>",
  "</div>",
  "</div>",
  "<div class=\"mt-auto space-y-4\">",
  "<div class=\"dewdrop-card rounded-[32px] p-6\">",
  "<h4 class=\"font-label-caps text-label-caps text-on-surface mb-4 uppercase tracking-widest flex items-center gap-2\">",
  "<span class=\"material-symbols-outlined text-[16px]\">dataset</span> Shared Workspace",
  "            </h4>",
  "<div class=\"space-y-3\">",
  "<div class=\"flex items-center justify-between text-xs p-2 hover:bg-black/5 rounded-lg cursor-pointer transition-colors\">",
  "<span class=\"flex items-center gap-2 text-on-surface\"><span class=\"material-symbols-outlined text-[14px] text-primary-container\">description</span> legacy_schema.json</span>",
  "<span class=\"text-on-surface-variant\">1.2mb</span>",
  "</div>",
  "<div class=\"flex items-center justify-between text-xs p-2 hover:bg-black/5 rounded-lg cursor-pointer transition-colors\">",
  "<span class=\"flex items-center gap-2 text-on-surface\"><span class=\"material-symbols-outlined text-[14px] text-secondary\">code</span> parser_v2.py</span>",
  "<span class=\"text-on-surface-variant\">4kb</span>",
  "</div>",
  "</div>",
  "</div>",
  "<div class=\"dewdrop-card rounded-[32px] p-6\">",
  "<h4 class=\"font-label-caps text-label-caps text-on-surface mb-4 uppercase tracking-widest\">Orchestration</h4>",
  "<div class=\"flex items-center justify-between mb-2\">",
  "<span class=\"text-xs text-on-surface-variant\">Task Completion</span>",
  "<span class=\"text-xs font-bold text-primary-container\">65%</span>",
  "</div>",
  "<div class=\"h-1.5 bg-black/10 rounded-full overflow-hidden mb-6\">",
  "<div class=\"h-full bg-primary-container w-[65%] rounded-full\"></div>",
  "</div>",
  "<button class=\"w-full py-3 rounded-2xl border border-white/40 text-xs font-label-caps text-on-surface hover:bg-white/50 transition-all shadow-sm\">View Dependency Graph</button>",
  "</div>",
  "</div>",
  "</aside>",
  "</section>",
  "</main>",
  "</div>",
  "</body></html>"
].join("\n");

export function GroupWorkspacePage() {
  return (
    <iframe
      title="Group Workspace"
      srcDoc={pageHtml}
      sandbox="allow-scripts allow-same-origin allow-popups allow-forms"
      style={{ width: "100%", height: "100vh", border: 0, display: "block" }}
    />
  );
}

export default GroupWorkspacePage;
