import { useState, useMemo } from "react";
import {
  Search, Plus, MessageSquare, CheckCircle2, AlertTriangle,
} from "lucide-react";
import styles from "./GroupWorkspacePage.module.css";

/* ---- Types ---------------------------------------------- */
type TaskStatus = "backlog" | "active" | "review";
type ApprovalState = "pending" | "approved" | "changes";
type MemberPresence = "online" | "busy" | "offline";
type MemberFilter = "all" | MemberPresence;
type ConfirmationTone = "info" | "success" | "warning";
type Accent = "blue" | "cyan" | "purple" | "teal";

interface Member {
  initials: string;
  name: string;
  role: string;
  accent: Accent;
  presence: MemberPresence;
}

interface WorkspaceTask {
  id: string;
  title: string;
  summary: string;
  owner: string;
  status: TaskStatus;
  tag: string;
  progress: number;
}

interface FileItem {
  name: string;
  detail: string;
  size: string;
  accent: Accent;
}

interface ActivityItem {
  title: string;
  detail: string;
  time: string;
  accent: Accent;
}

interface SyncState {
  complete: boolean;
  fileCount: number;
  lastSyncedAt: string;
  progress: number;
  revision: number;
}

interface Confirmation {
  title: string;
  detail: string;
  tone: ConfirmationTone;
}

/* ---- Mock Data ------------------------------------------ */
const members: Member[] = [
  { initials: "DA", name: "DataAgent Alpha", role: "Schema extraction ready", accent: "blue", presence: "online" },
  { initials: "CS", name: "CodeSmith", role: "Parser tests running", accent: "purple", presence: "busy" },
  { initials: "SC", name: "Security-Core", role: "PII guard enabled", accent: "teal", presence: "online" },
  { initials: "XM", name: "Xavier", role: "Final review owner", accent: "cyan", presence: "online" },
];

const baseTasks: WorkspaceTask[] = [
  { id: "aliases", title: "Confirm legacy field aliases", summary: "Resolve conflicting aliases before parser merge.", owner: "DataAgent Alpha", status: "backlog", tag: "Mapping", progress: 20 },
  { id: "docs", title: "Update handoff notes", summary: "Add accepted masking rules to the shared document.", owner: "Xavier", status: "backlog", tag: "Docs", progress: 12 },
  { id: "parser", title: "Generate masked parser", summary: "Apply PII rules and produce reviewable test output.", owner: "CodeSmith", status: "active", tag: "Script", progress: 68 },
  { id: "snapshot", title: "Stage dry-run snapshot", summary: "Keep the preview channel current for reviewers.", owner: "DataAgent Alpha", status: "active", tag: "Sync", progress: 72 },
  { id: "policy", title: "Validate redaction policy", summary: "Confirm email and phone extension fields are masked.", owner: "Security-Core", status: "review", tag: "Security", progress: 94 },
  { id: "approve", title: "Approve parser v2", summary: "Diff is ready with masking checks and sample output.", owner: "Xavier", status: "review", tag: "Approval", progress: 82 },
];

const files: FileItem[] = [
  { name: "legacy_schema.json", detail: "Added by DataAgent Alpha", size: "1.2 MB", accent: "cyan" },
  { name: "parser_v2.py", detail: "Generated by CodeSmith", size: "4 KB", accent: "purple" },
  { name: "masking_rules.md", detail: "Approved by Security-Core", size: "18 KB", accent: "teal" },
  { name: "dry_run_snapshot.csv", detail: "Shared after sync preview", size: "860 KB", accent: "blue" },
];

const initialActivities: ActivityItem[] = [
  { title: "DataAgent Alpha added legacy_schema.json", detail: "Schema map is attached to the shared file area.", time: "10:42", accent: "cyan" },
  { title: "CodeSmith generated parser_v2.py", detail: "Task moved to review after test output arrived.", time: "10:47", accent: "purple" },
  { title: "Security-Core approved masking rules", detail: "PII fields are flagged before any sync action is visible.", time: "10:51", accent: "teal" },
];

const laneLabels: Record<TaskStatus, string> = {
  backlog: "Backlog",
  active: "In progress",
  review: "Review",
};

const memberFilterOptions: Array<{ id: MemberFilter; label: string }> = [
  { id: "all", label: "All" },
  { id: "online", label: "Online" },
  { id: "busy", label: "Busy" },
  { id: "offline", label: "Offline" },
];

const presenceLabels: Record<MemberPresence, string> = {
  online: "Online",
  busy: "Busy",
  offline: "Offline",
};

/* ---- Helpers -------------------------------------------- */
function nowLabel() {
  return new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
}

/* ---- Sub-components ------------------------------------- */

function AccentIcon({ accent, label }: { accent: Accent; label: string }) {
  const cls = accent === "blue" ? styles.accentIcon
    : accent === "cyan" ? `${styles.accentIcon} ${styles.accentIconCyan}`
    : accent === "purple" ? `${styles.accentIcon} ${styles.accentIconPurple}`
    : `${styles.accentIcon} ${styles.accentIconTeal}`;
  return <span className={cls}>{label}</span>;
}

function MemberAvatar({ member }: { member: Member }) {
  const accentCls = member.accent === "blue" ? ""
    : member.accent === "purple" ? styles.avatarPurple
    : member.accent === "teal" ? styles.avatarTeal
    : styles.avatarCyan;
  const presenceCls = member.presence === "busy" ? styles.avatarBusy
    : member.presence === "offline" ? styles.avatarOffline : "";
  return (
    <span className={[styles.avatar, accentCls, presenceCls].filter(Boolean).join(" ")}>
      {member.initials}
    </span>
  );
}

/* ---- Main Component ------------------------------------- */

export default function GroupWorkspacePage() {
  const [approval, setApproval] = useState<ApprovalState>("pending");
  const [taskOwner, setTaskOwner] = useState("Xavier");
  const [syncState, setSyncState] = useState<SyncState>({
    complete: false, fileCount: 12, lastSyncedAt: "Not synced", progress: 82, revision: 0,
  });
  const [activityLog, setActivityLog] = useState<ActivityItem[]>(initialActivities);
  const [workspaceMembers, setWorkspaceMembers] = useState<Member[]>(members);
  const [memberFilter, setMemberFilter] = useState<MemberFilter>("all");
  const [noteDraft, setNoteDraft] = useState("");
  const [confirmation, setConfirmation] = useState<Confirmation>({
    title: "Interactive workspace ready",
    detail: "Local controls are wired for review, sync, assignment, member presence, and notes.",
    tone: "info",
  });

  const showConfirmation = (next: Confirmation) => setConfirmation(next);

  const pushActivity = (a: Omit<ActivityItem, "time">) => {
    setActivityLog((cur) => [{ ...a, time: nowLabel() }, ...cur].slice(0, 8));
  };

  const approved = approval === "approved";
  const needsEdits = approval === "changes";
  const visibleMembers = workspaceMembers.filter((m) => memberFilter === "all" || m.presence === memberFilter);
  const onlineCount = workspaceMembers.filter((m) => m.presence === "online").length;
  const busyCount = workspaceMembers.filter((m) => m.presence === "busy").length;
  const approvalLabel = approved ? "Approved" : needsEdits ? "Changes requested" : "Awaiting approval";
  const approvalLocked = !approved;

  const syncedFiles: FileItem[] = syncState.revision
    ? [{ name: `sync_receipt_r${syncState.revision}.txt`, detail: `Created by dry-run sync at ${syncState.lastSyncedAt}`, size: "2 KB", accent: "blue" }]
    : [];
  const workspaceFiles = [...files, ...syncedFiles];

  const tasks = useMemo(() => baseTasks.map((t) => {
    if (t.id === "approve") {
      return {
        ...t, owner: taskOwner,
        progress: approval === "approved" ? 100 : approval === "changes" ? 60 : 82,
        summary: approval === "approved" ? "Approved for dry-run sync. Snapshot action is unlocked."
          : approval === "changes" ? "Reviewer requested one visible edit before approval." : t.summary,
      };
    }
    if (t.id === "snapshot" && syncState.complete) {
      return { ...t, progress: syncState.progress, summary: `Dry-run snapshot synced at ${syncState.lastSyncedAt}.` };
    }
    return t;
  }), [approval, syncState.complete, syncState.lastSyncedAt, syncState.progress, taskOwner]);

  const laneTasks = (status: TaskStatus) => tasks.filter((t) => t.status === status);

  const approveParser = () => {
    setApproval("approved");
    setSyncState((cur) => ({ ...cur, complete: false, progress: Math.max(cur.progress, 91) }));
    pushActivity({ title: "Xavier approved parser v2", detail: "Sync controls are unlocked and the review task is marked complete.", accent: "blue" });
    showConfirmation({ title: "Approval saved", detail: "Parser v2 is approved. The snapshot sync button is now enabled.", tone: "success" });
  };

  const requestEdits = () => {
    setApproval("changes");
    setSyncState((cur) => ({ ...cur, complete: false, progress: 74 }));
    pushActivity({ title: "Xavier requested parser edits", detail: "Sync was locked again until the requested changes are resolved.", accent: "purple" });
    showConfirmation({ title: "Changes requested", detail: "Approval state changed and sync is locked while the review is open.", tone: "warning" });
  };

  const assignSecurity = () => {
    const next = taskOwner === "Security-Core" ? "Xavier" : "Security-Core";
    setTaskOwner(next);
    pushActivity({ title: `Approval assigned to ${next}`, detail: "Task owner changed on the review card, board, and sync checklist.", accent: "teal" });
    showConfirmation({ title: "Review reassigned", detail: `Parser v2 is now assigned to ${next}.`, tone: "info" });
  };

  const syncSnapshot = () => {
    if (!approved) {
      showConfirmation({ title: "Sync is locked", detail: "Approve parser v2 before syncing the shared snapshot.", tone: "warning" });
      return;
    }
    const syncedAt = nowLabel();
    const nextRev = syncState.revision + 1;
    setSyncState((cur) => ({ complete: true, fileCount: cur.fileCount + 1, lastSyncedAt: syncedAt, progress: 100, revision: nextRev }));
    pushActivity({ title: "Dry-run snapshot synced", detail: `Workspace files updated and sync receipt generated at ${syncedAt}.`, accent: "cyan" });
    showConfirmation({ title: "Snapshot synced", detail: `Files, progress, and last sync time now reflect revision ${nextRev}.`, tone: "success" });
  };

  const cycleMemberPresence = (memberName: string) => {
    const sel = workspaceMembers.find((m) => m.name === memberName);
    if (!sel) return;
    const next: MemberPresence = sel.presence === "online" ? "busy" : sel.presence === "busy" ? "offline" : "online";
    setWorkspaceMembers((cur) => cur.map((m) => m.name === memberName ? { ...m, presence: next } : m));
    pushActivity({ title: `${sel.name} is now ${presenceLabels[next].toLowerCase()}`, detail: "Member presence changed locally and the member filter counters updated.", accent: sel.accent });
    showConfirmation({ title: "Member status updated", detail: `${sel.name} switched to ${presenceLabels[next]}.`, tone: next === "offline" ? "warning" : "info" });
  };

  const selectMemberFilter = (filter: MemberFilter) => {
    setMemberFilter(filter);
    showConfirmation({ title: "Member filter changed", detail: filter === "all" ? "Showing every workspace member." : `Showing only members marked ${presenceLabels[filter].toLowerCase()}.`, tone: "info" });
  };

  const sendNote = () => {
    const trimmed = noteDraft.trim();
    if (!trimmed) {
      showConfirmation({ title: "Note is empty", detail: "Write a collaboration note before sending it to the activity flow.", tone: "warning" });
      return;
    }
    pushActivity({ title: "Collaboration note sent", detail: trimmed, accent: "blue" });
    setNoteDraft("");
    showConfirmation({ title: "Note posted", detail: "The note was added to the activity flow and the composer was cleared.", tone: "success" });
  };

  const fillComposer = (token: string, label: string) => {
    setNoteDraft((cur) => `${cur}${cur ? " " : ""}${token}`);
    showConfirmation({ title: label, detail: "Composer content was updated locally.", tone: "info" });
  };

  const createLocalFile = () => {
    setSyncState((cur) => ({ ...cur, fileCount: cur.fileCount + 1 }));
    pushActivity({ title: "Local file placeholder added", detail: "Shared file count increased without contacting a backend.", accent: "cyan" });
    showConfirmation({ title: "File placeholder added", detail: "The file counter changed locally for this interactive preview.", tone: "info" });
  };

  const exportSummary = () => {
    pushActivity({ title: "Workspace summary prepared", detail: "Export is represented as a local confirmation for this preview.", accent: "teal" });
    showConfirmation({ title: "Export prepared", detail: "No file was downloaded. The action is captured in the activity flow.", tone: "success" });
  };

  return (
    <div className={styles.page}>
      <div className={styles.shell}>
        {/* Left: Nav + Members */}
        <aside className={`${styles.side} ${styles.glass}`}>
          <div className={styles.brand}>
            <span className={styles.mark}>AH</span>
            <div className={`${styles.truncate} ${styles.title}`}>
              <p className={styles.eyebrow}>AgentHub</p>
              <h2>Group Workspace</h2>
            </div>
          </div>

          <section className={styles.section}>
            <div className={styles.sectionHead}>
              <h2>Spaces</h2>
              <span className={`${styles.pill} ${styles.pillCyan}`}>
                <span className={`${styles.dot} ${styles.dotCyan}`} />
                Live
              </span>
            </div>
            <div className={styles.stack}>
              <div className={`${styles.nav} ${styles.navActive}`}>
                <AccentIcon accent="blue" label="S" />
                <div className={styles.truncate}>
                  <strong>Legacy Migration</strong>
                  <p className={`${styles.textTiny} ${styles.truncate}`}>Cross-system sync</p>
                </div>
              </div>
              <div className={styles.nav}>
                <AccentIcon accent="purple" label="R" />
                <div className={styles.truncate}>
                  <strong>Mapping Review</strong>
                  <p className={`${styles.textTiny} ${styles.truncate}`}>2 approvals open</p>
                </div>
              </div>
              <div className={styles.nav}>
                <AccentIcon accent="cyan" label="F" />
                <div className={styles.truncate}>
                  <strong>Shared Files</strong>
                  <p className={`${styles.textTiny} ${styles.truncate}`}>{syncState.fileCount} documents</p>
                </div>
              </div>
            </div>
          </section>

          <section className={styles.section}>
            <div className={styles.sectionHead}>
              <h2>Members</h2>
              <span className={styles.textTiny}>{onlineCount} online / {busyCount} busy</span>
            </div>
            <div className={styles.filters} role="group" aria-label="Filter members by status">
              {memberFilterOptions.map((opt) => (
                <button
                  key={opt.id}
                  className={opt.id === memberFilter ? `${styles.filter} ${styles.filterActive}` : styles.filter}
                  type="button"
                  onClick={() => selectMemberFilter(opt.id)}
                >
                  {opt.label}
                </button>
              ))}
            </div>
            <div className={styles.stack}>
              {visibleMembers.map((m) => (
                <button
                  key={m.name}
                  className={styles.member}
                  type="button"
                  onClick={() => cycleMemberPresence(m.name)}
                >
                  <MemberAvatar member={m} />
                  <div className={styles.truncate}>
                    <strong>{m.name}</strong>
                    <p className={`${styles.textTiny} ${styles.truncate}`}>
                      {m.role} - {presenceLabels[m.presence]}
                    </p>
                  </div>
                </button>
              ))}
              {visibleMembers.length === 0 ? (
                <div className={styles.empty}>No members match this status filter.</div>
              ) : null}
            </div>
          </section>

          <div className={styles.spacer} />
          <section className={styles.sync}>
            <div className={styles.row}>
              <span className={styles.eyebrow}>Workspace Health</span>
              <span className={syncState.complete ? `${styles.pill} ${styles.pillGreen}` : `${styles.pill} ${styles.pillCyan}`}>
                {syncState.complete ? "Synced" : "Stable"}
              </span>
            </div>
            <p className={styles.textSmall}>Local UI state only. Last sync: {syncState.lastSyncedAt}.</p>
          </section>
        </aside>

        {/* Center: Main content */}
        <main className={styles.main}>
          <header className={`${styles.top} ${styles.glass}`}>
            <div className={styles.title}>
              <p className={styles.eyebrow}>Legacy Migration Room</p>
              <h1>Shared operations cockpit</h1>
              <p className={styles.textSmall}>
                Members, tasks, files, approvals, and sync status stay visible in one working surface.
              </p>
            </div>
            <div className={styles.actions}>
              <div className={styles.searchBox} aria-label="Search workspace">
                <Search size={14} />
                <span className={styles.truncate}>tasks, files, members</span>
              </div>
              <button className={styles.button} type="button" onClick={exportSummary}>
                Export
              </button>
              <button className={`${styles.button} ${styles.buttonPrimary}`} type="button" onClick={assignSecurity}>
                Assign review
              </button>
            </div>
          </header>

          <section className={styles.stats}>
            <div className={`${styles.stat} ${styles.glass}`}>
              <strong>{onlineCount}</strong>
              <p className={styles.textSmall}>Online members</p>
            </div>
            <div className={`${styles.stat} ${styles.glass}`}>
              <strong>{tasks.length}</strong>
              <p className={styles.textSmall}>Shared tasks</p>
            </div>
            <div className={`${styles.stat} ${styles.glass}`}>
              <strong>{syncState.fileCount}</strong>
              <p className={styles.textSmall}>Workspace files</p>
            </div>
            <div className={`${styles.stat} ${styles.glass}`}>
              <strong>{syncState.progress}%</strong>
              <p className={styles.textSmall}>Sync readiness</p>
            </div>
          </section>

          <section
            className={`${styles.confirmation} ${styles.glass} ${confirmation.tone === "success" ? styles.confirmationSuccess : confirmation.tone === "warning" ? styles.confirmationWarning : ""}`}
            aria-live="polite"
          >
            <div>
              <strong>{confirmation.title}</strong>
              <p className={styles.textSmall}>{confirmation.detail}</p>
            </div>
            <button
              className={styles.iconBtn}
              type="button"
              aria-label="Dismiss confirmation"
              onClick={() => showConfirmation({ title: "Status bar cleared", detail: "The next local action will appear here.", tone: "info" })}
            >
              <Plus size={14} style={{ transform: "rotate(45deg)" }} />
            </button>
          </section>

          <section className={styles.content}>
            <div className={`${styles.column} ${styles.glass}`}>
              <div className={styles.sectionHead}>
                <div className={styles.title}>
                  <p className={styles.eyebrow}>Shared Task Board</p>
                  <h2>Current coordination plan</h2>
                </div>
                <span className={`${styles.pill} ${styles.pillPurple}`}>Auto assigned</span>
              </div>

              <div className={styles.board}>
                {(Object.keys(laneLabels) as TaskStatus[]).map((status) => (
                  <section className={styles.lane} key={status}>
                    <div className={styles.row}>
                      <h3 className={styles.laneTitle}>{laneLabels[status]}</h3>
                      <span className={styles.pill}>{laneTasks(status).length}</span>
                    </div>
                    {laneTasks(status).map((task) => (
                      <article className={styles.card} key={task.id}>
                        <div className={styles.row}>
                          <span className={task.status === "review" ? `${styles.pill} ${styles.pillPurple}` : `${styles.pill} ${styles.pillCyan}`}>
                            {task.tag}
                          </span>
                          <span className={styles.textTiny}>{task.progress}%</span>
                        </div>
                        <h3>{task.title}</h3>
                        <p className={styles.textSmall}>{task.summary}</p>
                        <div className={styles.progress} aria-label={`${task.title} progress`}>
                          <span className={styles.progressFill} style={{ width: `${task.progress}%` }} />
                        </div>
                        <div className={styles.row}>
                          <span className={styles.textTiny}>Owner: {task.owner}</span>
                          {task.id === "approve" ? (
                            <button className={styles.button} type="button" onClick={assignSecurity}>
                              Reassign
                            </button>
                          ) : null}
                        </div>
                      </article>
                    ))}
                  </section>
                ))}
              </div>
            </div>

            <aside className={`${styles.feed} ${styles.glass}`}>
              <div className={styles.sectionHead}>
                <div className={styles.title}>
                  <p className={styles.eyebrow}>Activity Flow</p>
                  <h2>Workspace pulse</h2>
                </div>
                <span className={syncState.complete ? `${styles.pill} ${styles.pillGreen}` : `${styles.pill} ${styles.pillCyan}`}>
                  <span className={styles.dot} />
                  {syncState.complete ? "Synced" : "Live"}
                </span>
              </div>

              <div className={styles.activityList}>
                {activityLog.map((a, i) => (
                  <div className={styles.activity} key={`${a.title}-${i}`}>
                    <AccentIcon accent={a.accent} label={a.accent.slice(0, 1).toUpperCase()} />
                    <div className={styles.truncate}>
                      <strong>{a.title}</strong>
                      <p className={`${styles.textSmall} ${styles.truncate}`}>{a.detail}</p>
                      <span className={styles.textTiny}>{a.time}</span>
                    </div>
                  </div>
                ))}
              </div>

              <div className={styles.composer}>
                <div className={styles.row}>
                  <div className={styles.actions}>
                    <button className={styles.iconBtn} type="button" aria-label="Mention member" onClick={() => fillComposer("@group", "Mention inserted")}>
                      @
                    </button>
                    <button className={styles.iconBtn} type="button" aria-label="Attach file" onClick={() => fillComposer("[attachment]", "Attachment marker inserted")}>
                      <Plus size={14} />
                    </button>
                    <button className={styles.iconBtn} type="button" aria-label="Create task" onClick={() => fillComposer("#task", "Task marker inserted")}>
                      T
                    </button>
                  </div>
                  <span className={`${styles.pill} ${styles.pillCyan}`}>@group</span>
                </div>
                <textarea
                  aria-label="Workspace message"
                  placeholder="Send a coordination note to this workspace..."
                  value={noteDraft}
                  onChange={(e) => setNoteDraft(e.target.value)}
                />
                <div className={styles.row}>
                  <span className={styles.textTiny}>
                    {noteDraft.trim() ? `${noteDraft.trim().length} characters ready` : "Draft is empty."}
                  </span>
                  <button
                    className={`${styles.button} ${styles.buttonPrimary}`}
                    type="button"
                    disabled={!noteDraft.trim()}
                    onClick={sendNote}
                  >
                    Send note
                  </button>
                </div>
              </div>
            </aside>
          </section>
        </main>

        {/* Right: Approval + Sync + Files */}
        <aside className={`${styles.right} ${styles.glass}`}>
          <section className={styles.section}>
            <div className={styles.sectionHead}>
              <div className={styles.title}>
                <p className={styles.eyebrow}>Approval</p>
                <h2>Parser v2 ready</h2>
              </div>
              <span className={approved ? `${styles.pill} ${styles.pillGreen}` : needsEdits ? `${styles.pill} ${styles.pillPurple}` : styles.pill}>
                {approvalLabel}
              </span>
            </div>
            <div className={styles.approval}>
              <div className={styles.row}>
                <strong>{approvalLabel}</strong>
                <span className={styles.textTiny}>Owner: {taskOwner}</span>
              </div>
              <p className={styles.textSmall}>
                {approved
                  ? "Parser diff is approved. Sync controls are now visible and enabled."
                  : needsEdits
                    ? "A requested-edit state is visible on the review card and board."
                    : "Parser diff is staged, security checks passed, and sync remains locked until approval."}
              </p>
              <div className={styles.actions}>
                <button className={`${styles.button} ${styles.buttonWarning}`} type="button" onClick={requestEdits}>
                  Request edits
                </button>
                <button className={`${styles.button} ${styles.buttonPrimary}`} type="button" onClick={approveParser}>
                  Approve
                </button>
              </div>
            </div>
          </section>

          <section className={styles.section}>
            <div className={styles.sectionHead}>
              <div className={styles.title}>
                <p className={styles.eyebrow}>Sync Status</p>
                <h2>Shared snapshot</h2>
              </div>
              <span className={syncState.complete ? `${styles.pill} ${styles.pillGreen}` : `${styles.pill} ${styles.pillCyan}`}>
                {syncState.progress}%
              </span>
            </div>
            <div className={styles.sync}>
              <div className={styles.row}>
                <span className={styles.textSmall}>Dry-run readiness</span>
                <strong>{syncState.complete ? "Complete" : approved ? "Unlocked" : "Locked"}</strong>
              </div>
              <div className={styles.progress} aria-label="Dry-run readiness">
                <span className={styles.progressFill} style={{ width: `${syncState.progress}%` }} />
              </div>
              <button
                className={`${styles.button} ${styles.buttonPrimary}`}
                type="button"
                disabled={approvalLocked}
                onClick={syncSnapshot}
              >
                {syncState.complete ? "Sync again" : approved ? "Sync snapshot" : "Approve to sync"}
              </button>
              <div className={styles.checks}>
                <div className={styles.check}>
                  <span className={`${styles.dot} ${styles.dotCyan}`} />
                  <div>
                    <strong>Files indexed</strong>
                    <p className={styles.textTiny}>{syncState.fileCount} workspace files available.</p>
                  </div>
                </div>
                <div className={styles.check}>
                  <span className={`${styles.dot} ${styles.dotPurple}`} />
                  <div>
                    <strong>Assignments visible</strong>
                    <p className={styles.textTiny}>Review owner is {taskOwner}.</p>
                  </div>
                </div>
                <div className={styles.check}>
                  <span className={styles.dot} />
                  <div>
                    <strong>Last sync</strong>
                    <p className={styles.textTiny}>{syncState.lastSyncedAt}.</p>
                  </div>
                </div>
              </div>
            </div>
          </section>

          <section className={styles.section}>
            <div className={styles.sectionHead}>
              <div className={styles.title}>
                <p className={styles.eyebrow}>Shared Files</p>
                <h2>Workspace documents</h2>
              </div>
              <button className={styles.iconBtn} type="button" aria-label="Add file" onClick={createLocalFile}>
                <Plus size={14} />
              </button>
            </div>
            <div className={styles.stack}>
              {workspaceFiles.map((f) => (
                <div className={styles.fileItem} key={f.name}>
                  <AccentIcon accent={f.accent} label={f.name.slice(0, 1).toUpperCase()} />
                  <div className={styles.truncate}>
                    <strong>{f.name}</strong>
                    <p className={`${styles.textTiny} ${styles.truncate}`}>{f.detail}</p>
                  </div>
                  <span className={styles.textTiny}>{f.size}</span>
                </div>
              ))}
              {workspaceFiles.length === 0 ? (
                <div className={styles.empty}>No files are visible in this workspace.</div>
              ) : null}
            </div>
          </section>
        </aside>
      </div>
    </div>
  );
}
