export type {
  HealthResponse,
  Project,
  ProjectMemory,
  Conversation,
  Thread,
  ThreadItem,
  ThreadItemKind,
  Message,
  Runner,
  Run,
  RunStatus,
  StartRunRequest,
  RunLogs,
  RunDiff,
  DiffFile,
  Approval,
  Artifact,
  Preview,
  Workspace,
  WorkspaceFile,
  PageInfo,
  ListResponse,
} from './types';

export type {
  EventEnvelope,
  EventScope,
  AnyEvent,
  ProjectCreatedEvent,
  ProjectUpdatedEvent,
  ThreadCreatedEvent,
  ThreadUpdatedEvent,
  MessageCreatedEvent,
  MessageDeltaEvent,
  ItemCreatedEvent,
  ItemUpdatedEvent,
  RunnerOnlineEvent,
  RunnerOfflineEvent,
  RunQueuedEvent,
  RunStartedEvent,
  RunStatusChangedEvent,
  RunOutputEvent,
  RunOutputBatchEvent,
  RunFinishedEvent,
  RunFailedEvent,
  ApprovalRequestedEvent,
  ApprovalDecidedEvent,
  ArtifactCreatedEvent,
  PreviewReadyEvent,
  ErrorEvent,
} from './events';

export { parseError, isErrorResponse, AppError } from './errors';

export {
  setBaseUrl,
  getBaseUrl,
  getHealth,
  listProjects,
  getProject,
  createProject,
  getProjectMemory,
  listThreads,
  getThread,
  createThread,
  updateThread,
  archiveThread,
  listThreadItems,
  createThreadMessage,
  listRunners,
  getRunner,
  pingRunner,
  listRuns,
  getRun,
  startRun,
  cancelRun,
  listRunItems,
  getRunLogs,
  getRunDiff,
  listApprovals,
  getApproval,
  decideApproval,
  listArtifacts,
  getArtifact,
  getArtifactContent,
  applyArtifact,
  discardArtifact,
  listPreviews,
  getPreview,
  createPreview,
  getWorkspace,
  listWorkspaceFiles,
  readWorkspaceFile,
} from './apiClient';

export { EventClient } from './eventClient';
export type { EventListener, EventClientOptions } from './eventClient';

export {
  mockProject,
  mockProjects,
  mockThreads,
  mockMessages,
  mockThreadItems,
  mockRunners,
  mockRuns,
  mockApprovals,
  mockArtifacts,
  mockPreviews,
  mockWorkspaces,
  mockWorkspaceFiles,
  MockEventStream,
  playRunLifecycle,
  playMessageStream,
} from './mock';
