export type {
  HealthResponse,
  Project,
  ProjectMemory,
  Conversation,
  Thread,
  ThreadItem,
  ThreadItemKind,
  Message,
  Runner,
  Run,
  RunInfo,
  RunStatus,
  StartRunRequest,
  AgentCapabilities,
  AgentInfo,
  ThreadInfo,
  RunLogs,
  RunDiff,
  Approval,
  Artifact,
  Preview,
  Workspace,
  WorkspaceFile,
  PageInfo,
  ListResponse,
} from './types';

export type {
  EventEnvelope,
  EventScope,
  ProjectCreatedEvent,
  ProjectUpdatedEvent,
  ThreadCreatedEvent,
  ThreadUpdatedEvent,
  MessageCreatedEvent,
  MessageDeltaEvent,
  ItemCreatedEvent,
  ItemUpdatedEvent,
  RunnerOnlineEvent,
  RunnerOfflineEvent,
  RunQueuedEvent,
  RunStartedEvent,
  RunStatusChangedEvent,
  RunOutputEvent,
  RunOutputBatchEvent,
  RunFinishedEvent,
  RunFailedEvent,
  ApprovalRequestedEvent,
  ApprovalDecidedEvent,
  ArtifactCreatedEvent,
  PreviewReadyEvent,
  ErrorEvent,
  AnyEvent,
} from './events';

export { parseError, isErrorResponse, AppError } from './errors';

export { buildTree, flattenTree } from './tree';
export type { TreeNode } from './tree';

export { normalizeDiffs, parseUnifiedDiff } from './diff';
export type { DiffFile, DiffHunk, DiffLine } from './diff';

export {
  normalize,
  text as diffText,
  parseUnifiedPatch,
} from './diff';
export type {
  ViewDiff,
  LegacyDiff,
  ReviewDiff,
} from './diff';

export {
  estimateTokens,
  breakdownContext,
  toSegments,
  formatTokens,
  formatCost,
} from './context/breakdown';
export type {
  ContextBreakdown,
  BreakdownSegment,
  SessionMetrics,
} from './context/breakdown';

export { HUB_EVENTS } from './hubEvents';
export type { HubEventType } from './hubEvents';

export {
  createHubClient,
  HubError,
  isHubResponseEnvelope,
  parseHubError,
  unwrapHubResponse,
} from './hubClient';
export type {
  AddAgentToSessionRequest,
  AuthResponse,
  ChangePasswordRequest,
  Contact,
  ContactInfo,
  CreateGroupSessionRequest,
  CreatePrivateSessionRequest,
  CustomAgentRequest,
  Device,
  FriendRequestInfo,
  HubAddAgentToSessionRequest,
  HubAgentDispatchFrame,
  HubAgentDispatchPayload,
  HubAgentCancelFrame,
  HubAgentCancelPayload,
  HubAgentDoneFrame,
  HubAgentDonePayload,
  HubAgentFailedFrame,
  HubAgentFailedPayload,
  HubAgentStreamFrame,
  HubAgentStreamPayload,
  HubAgentTask,
  HubAgentTaskStatus,
  HubAuthResponse,
  HubChangePasswordRequest,
  HubClient,
  HubClientOptions,
  HubContactInfo,
  HubCreateGroupSessionRequest,
  HubCreatePrivateSessionRequest,
  HubCreateSessionResponse,
  HubCustomAgent,
  HubCustomAgentRequest,
  HubDevice,
  HubDeviceKickedFrame,
  HubDeviceKickedPayload,
  HubDeviceOfflineFrame,
  HubDeviceOnlineFrame,
  HubDevicePresencePayload,
  HubFrame,
  HubFriendAcceptedFrame,
  HubFriendEventPayload,
  HubFriendRequestFrame,
  HubFriendRequest,
  HubKnownFrame,
  HubLoginRequest,
  HubMessage,
  HubNotification,
  HubNotificationNewFrame,
  HubRegisterDeviceRequest,
  HubRegisterRequest,
  HubResponseEnvelope,
  HubSearchResult,
  HubSendMessageRequest,
  HubSendMessageResponse,
  HubSession,
  HubSessionMember,
  HubTaskAckRequest,
  HubTaskDoneRequest,
  HubTaskFailRequest,
  HubTaskRunRequest,
  HubTaskStreamRequest,
  HubTriggerAgentTaskRequest,
  HubUpdateProfileRequest,
  HubUpdateSessionInfoRequest,
  HubUpdateSessionSettingsRequest,
  HubUserProfile,
  LoginRequest,
  MessageResponse,
  RegisterDeviceRequest,
  RegisterRequest,
  ReplyToInfo,
  SearchResult,
  SendMessageRequest,
  SendMessageResponse,
  Session,
  SessionMember,
  UpdateProfileRequest,
  UserProfile,
} from './hubClient';

export {
  setBaseUrl,
  getBaseUrl,
  getHealth,
  listProjects,
  getProject,
  createProject,
  getProjectMemory,
  listThreads,
  getThread,
  createThread,
  updateThread,
  archiveThread,
  listThreadItems,
  createThreadMessage,
  listRunners,
  getRunner,
  pingRunner,
  listRuns,
  getRun,
  startRun,
  cancelRun,
  listRunItems,
  getRunLogs,
  getRunDiff,
  listApprovals,
  getApproval,
  decideApproval,
  listArtifacts,
  getArtifact,
  getArtifactContent,
  applyArtifact,
  discardArtifact,
  listPreviews,
  getPreview,
  createPreview,
  getWorkspace,
  listWorkspaceFiles,
  readWorkspaceFile,
} from './apiClient';

export { EventClient } from './eventClient';
export type {
  EventClientOptions,
  EventConnectionListener,
  EventConnectionStatus,
  EventListener,
} from './eventClient';

export {
  createWorkbenchState,
  initialWorkbenchState,
  workbenchReducer,
} from './workbenchState';
export type {
  WorkbenchAction,
  WorkbenchConnectionStatus,
  WorkbenchSnapshot,
  WorkbenchState,
} from './workbenchState';
export {
  getWorkbenchCatalogState,
  getWorkbenchDataMode,
  getWorkbenchSectionSource,
  workbenchDataModeLabels,
  workbenchDataModeTones,
} from './workbenchDataMode';
export type {
  WorkbenchCatalogState,
  WorkbenchCatalogTone,
  WorkbenchDataMode,
  WorkbenchSectionSource,
  WorkbenchSectionSourceInput,
} from './workbenchDataMode';

export {
  SURFACE_METADATA,
  SURFACE_STATUS_METADATA,
  getSurfaceByDesktopSectionId,
  getSurfaceByWebRoute,
  getSurfaceMetadata,
  getSurfaceStatusMetadata,
  getSurfacesByCategory,
  surfaceMetadataById,
  surfaceStatusById,
} from './surfaceMetadata';
export type {
  SurfaceCategory,
  SurfaceId,
  SurfaceMetadata,
  SurfacePlatform,
  SurfaceStatus,
  SurfaceStatusMetadata,
} from './surfaceMetadata';

export {
  mockProject,
  mockProjects,
  mockThreads,
  mockMessages,
  mockThreadItems,
  mockRunners,
  mockRuns,
  mockApprovals,
  mockArtifacts,
  mockPreviews,
  mockWorkspaces,
  mockWorkspaceFiles,
  MockEventStream,
  playRunLifecycle,
  playMessageStream,
} from './mock';
