export { createMockTerminalPort } from './createMockPlatform';
export { resolveEvidencePreviewTarget } from './previewTargets';
export type {
  AgentHubPlatform,
  AgentHubSurface,
  ApplyAllRunDiffsInput,
  ApplyRunDiffInput,
  AttachmentPort,
  ConversationKind,
  ConversationPort,
  HostDiagnosticsPort,
  LocalCliDiscoveryItem,
  LocalCliDiscoveryManifest,
  LocalCliRuntimeId,
  PreviewPort,
  RedispatchTaskResult,
  RunDiffHunkDecision,
  RunPort,
  RuntimeEvidenceContentRef,
  RuntimeSessionSummary,
  SurfaceCapabilities,
  TerminalPort,
  TerminalResizePayload,
  TerminalSession,
  TerminalSessionId,
  TerminalSessionStatus,
  TerminalSpawnOptions,
  TerminalWritePayload,
  WorkbenchAgent,
  WorkbenchConversation,
  WorkspaceFileEntry,
  WorkspaceFilesPort,
  WorkspaceGitChange,
  WorkspaceGitCommit,
  WorkspaceGitPort,
} from './types';
