const pageHtml: string = [
  "<!DOCTYPE html>",
  "",
  "<html lang=\"en\" style=\"\"><head>",
  "<meta charset=\"utf-8\"/>",
  "<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\"/>",
  "<title>AetherFlow | AI Multi-Agent Missions</title>",
  "<script src=\"https://cdn.tailwindcss.com?plugins=forms,container-queries\"></script>",
  "<link href=\"https://fonts.googleapis.com/css2?family=Hanken+Grotesk:wght@400;500;600;700&amp;family=JetBrains+Mono:wght@400;500&amp;display=swap\" rel=\"stylesheet\"/>",
  "<link href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&amp;display=swap\" rel=\"stylesheet\"/>",
  "<style>",
  "        .dewdrop-card {",
  "            background: linear-gradient(135deg, rgba(255, 255, 255, 0.15) 0%, rgba(255, 255, 255, 0.05) 100%);",
  "            backdrop-filter: blur(80px) saturate(150%);",
  "            -webkit-backdrop-filter: blur(80px) saturate(150%);",
  "            border: 1.5px solid transparent;",
  "            background-clip: padding-box;",
  "            box-shadow:",
  "                0 20px 40px -10px rgba(0, 120, 212, 0.15),",
  "                0 10px 20px -5px rgba(0, 120, 212, 0.1),",
  "                inset 2px 2px 4px rgba(255, 255, 255, 0.6),",
  "                inset -2px -2px 4px rgba(255, 255, 255, 0.1);",
  "            position: relative;",
  "            transition: all 0.4s cubic-bezier(0.23, 1, 0.32, 1);",
  "        }",
  "",
  "        .dewdrop-card::after {",
  "            content: '';",
  "            position: absolute;",
  "            inset: 0;",
  "            border-radius: inherit;",
  "            padding: 1.5px;",
  "            background: linear-gradient(135deg, rgba(255, 255, 255, 0.9) 0%, rgba(255, 255, 255, 0.2) 30%, rgba(255, 255, 255, 0) 100%);",
  "            -webkit-mask: linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0);",
  "            -webkit-mask-composite: xor;",
  "            mask-composite: exclude;",
  "            pointer-events: none;",
  "        }",
  "",
  "        .dewdrop-card::before {",
  "            content: '';",
  "            position: absolute;",
  "            top: 6px;",
  "            left: 6px;",
  "            width: 16px;",
  "            height: 16px;",
  "            border-radius: 50%;",
  "            background: radial-gradient(circle, rgba(255,255,255,0.9) 0%, rgba(255,255,255,0) 70%);",
  "            pointer-events: none;",
  "            z-index: 10;",
  "        }",
  "",
  "        .dewdrop-card:hover {",
  "            transform: translateY(-4px) scale(1.01);",
  "            box-shadow:",
  "                0 30px 50px -12px rgba(0, 120, 212, 0.2),",
  "                inset 2px 2px 5px rgba(255, 255, 255, 0.8),",
  "                inset -2px -2px 5px rgba(255, 255, 255, 0.2);",
  "            background: linear-gradient(135deg, rgba(255, 255, 255, 0.25) 0%, rgba(255, 255, 255, 0.1) 100%);",
  "        }",
  "",
  "        .dewdrop-panel {",
  "            background: rgba(255, 255, 255, 0.1);",
  "            backdrop-filter: blur(64px) saturate(150%);",
  "            -webkit-backdrop-filter: blur(64px) saturate(150%);",
  "            border: 1.5px solid rgba(255, 255, 255, 0.1);",
  "            border-top-color: rgba(255, 255, 255, 0.8);",
  "            border-left-color: rgba(255, 255, 255, 0.6);",
  "            box-shadow:",
  "                0 20px 50px -10px rgba(0, 120, 212, 0.12),",
  "                inset 1px 1px 2px rgba(255, 255, 255, 0.7),",
  "                inset -1px -1px 2px rgba(255, 255, 255, 0.1);",
  "            position: relative;",
  "            overflow: hidden;",
  "        }",
  "",
  "        .dewdrop-panel::before {",
  "            content: '';",
  "            position: absolute;",
  "            top: 0;",
  "            left: 0;",
  "            width: 120px;",
  "            height: 120px;",
  "            background: radial-gradient(circle at 0 0, rgba(255,255,255,0.7) 0%, rgba(255,255,255,0) 70%);",
  "            pointer-events: none;",
  "        }",
  "",
  "        .luminous-button {",
  "            background: #0078d4;",
  "            transition: all 0.3s ease;",
  "            box-shadow: 0 4px 15px rgba(0, 120, 212, 0.4);",
  "        }",
  "        .luminous-button:hover {",
  "            background: #005faa;",
  "            transform: scale(1.02);",
  "            box-shadow: 0 6px 20px rgba(0, 120, 212, 0.6);",
  "        }",
  "",
  "        .custom-scrollbar::-webkit-scrollbar {",
  "            width: 4px;",
  "        }",
  "        .custom-scrollbar::-webkit-scrollbar-track {",
  "            background: transparent;",
  "        }",
  "        .custom-scrollbar::-webkit-scrollbar-thumb {",
  "            background: rgba(0, 0, 0, 0.2);",
  "            border-radius: 10px;",
  "        }",
  "        .agent-pill {",
  "            border-left-width: 2px;",
  "        }",
  "        .material-symbols-outlined {",
  "            font-variation-settings: 'FILL' 0, 'wght' 300, 'GRAD' 0, 'opsz' 24;",
  "        }",
  "    </style>",
  "<script id=\"tailwind-config\">",
  "  tailwind.config = {",
  "    darkMode: \"class\",",
  "    theme: {",
  "      extend: {",
  "        \"colors\": {",
  "                \"error-container\": \"#ffdad6\",",
  "                \"on-tertiary-fixed-variant\": \"#005046\",",
  "                \"on-error\": \"#ffffff\",",
  "                \"surface-container-high\": \"#e8e8e8\",",
  "                \"secondary\": \"#7615e6\",",
  "                \"on-error-container\": \"#93000a\",",
  "                \"surface-dim\": \"#dadada\",",
  "                \"on-secondary-container\": \"#fdf6ff\",",
  "                \"on-tertiary-fixed\": \"#00201b\",",
  "                \"error\": \"#ba1a1a\",",
  "                \"tertiary-container\": \"#0a8575\",",
  "                \"surface-container-highest\": \"#e2e2e2\",",
  "                \"surface\": \"#f9f9f9\",",
  "                \"outline-variant\": \"#c0c7d4\",",
  "                \"primary-container\": \"#0078d4\",",
  "                \"secondary-fixed-dim\": \"#d6baff\",",
  "                \"tertiary\": \"#006a5c\",",
  "                \"surface-bright\": \"#f9f9f9\",",
  "                \"surface-container-lowest\": \"#ffffff\",",
  "                \"primary\": \"#005faa\",",
  "                \"outline\": \"#717783\",",
  "                \"surface-variant\": \"#e2e2e2\",",
  "                \"on-background\": \"#1a1c1c\",",
  "                \"tertiary-fixed-dim\": \"#75d8c5\",",
  "                \"surface-container\": \"#eeeeee\",",
  "                \"surface-container-low\": \"#f3f3f3\",",
  "                \"on-primary-container\": \"#ffffff\",",
  "                \"tertiary-fixed\": \"#91f4e1\",",
  "                \"on-secondary\": \"#ffffff\",",
  "                \"on-primary-fixed\": \"#001c39\",",
  "                \"background\": \"#f9f9f9\",",
  "                \"primary-fixed\": \"#d3e3ff\",",
  "                \"on-surface-variant\": \"#404752\",",
  "                \"secondary-fixed\": \"#ecdcff\",",
  "                \"inverse-surface\": \"#2f3131\",",
  "                \"inverse-on-surface\": \"#f1f1f1\",",
  "                \"primary-fixed-dim\": \"#a3c9ff\",",
  "                \"on-secondary-fixed\": \"#270057\",",
  "                \"on-tertiary-container\": \"#ffffff\",",
  "                \"on-secondary-fixed-variant\": \"#5f00c0\",",
  "                \"surface-tint\": \"#0060ab\",",
  "                \"on-tertiary\": \"#ffffff\",",
  "                \"inverse-primary\": \"#a3c9ff\",",
  "                \"on-primary-fixed-variant\": \"#004883\",",
  "                \"on-surface\": \"#1a1c1c\",",
  "                \"on-primary\": \"#ffffff\",",
  "                \"secondary-container\": \"#9040ff\"",
  "        },",
  "        \"borderRadius\": {",
  "                \"DEFAULT\": \"0.25rem\",",
  "                \"lg\": \"0.5rem\",",
  "                \"xl\": \"0.75rem\",",
  "                \"full\": \"9999px\"",
  "        },",
  "        \"spacing\": {",
  "                \"margin-desktop\": \"48px\",",
  "                \"unit\": \"4px\",",
  "                \"margin-mobile\": \"16px\",",
  "                \"max-width\": \"1440px\",",
  "                \"gutter\": \"24px\",",
  "                \"stack-sm\": \"8px\",",
  "                \"stack-md\": \"16px\",",
  "                \"stack-lg\": \"24px\",",
  "                \"stack-xl\": \"48px\",",
  "                \"container-max\": \"1440px\"",
  "        },",
  "        \"fontFamily\": {",
  "                \"label-md\": [",
  "                        \"Hanken Grotesk\"",
  "                ],",
  "                \"headline-lg\": [",
  "                        \"Hanken Grotesk\"",
  "                ],",
  "                \"body-md\": [",
  "                        \"Hanken Grotesk\"",
  "                ],",
  "                \"headline-md\": [",
  "                        \"Hanken Grotesk\"",
  "                ],",
  "                \"display\": [",
  "                        \"Hanken Grotesk\"",
  "                ],",
  "                \"body-lg\": [",
  "                        \"Hanken Grotesk\"",
  "                ],",
  "                \"label-sm\": [",
  "                        \"Hanken Grotesk\"",
  "                ],",
  "                \"headline-lg-mobile\": [",
  "                        \"Hanken Grotesk\"",
  "                ],",
  "                \"display-lg\": [\"Hanken Grotesk\"],",
  "                \"code-sm\": [\"JetBrains Mono\"],",
  "                \"label-caps\": [\"JetBrains Mono\"],",
  "                \"display-lg-mobile\": [\"Hanken Grotesk\"]",
  "        },",
  "        \"fontSize\": {",
  "                \"label-md\": [",
  "                        \"14px\",",
  "                        {",
  "                                \"lineHeight\": \"1.4\",",
  "                                \"letterSpacing\": \"0.01em\",",
  "                                \"fontWeight\": \"500\"",
  "                        }",
  "                ],",
  "                \"headline-lg\": [",
  "                        \"32px\",",
  "                        {",
  "                                \"lineHeight\": \"1.2\",",
  "                                \"fontWeight\": \"600\"",
  "                        }",
  "                ],",
  "                \"body-md\": [",
  "                        \"16px\",",
  "                        {",
  "                                \"lineHeight\": \"1.5\",",
  "                                \"fontWeight\": \"400\"",
  "                        }",
  "                ],",
  "                \"headline-md\": [",
  "                        \"24px\",",
  "                        {",
  "                                \"lineHeight\": \"1.3\",",
  "                                \"fontWeight\": \"600\"",
  "                        }",
  "                ],",
  "                \"display\": [",
  "                        \"56px\",",
  "                        {",
  "                                \"lineHeight\": \"1.1\",",
  "                                \"letterSpacing\": \"-0.02em\",",
  "                                \"fontWeight\": \"700\"",
  "                        }",
  "                ],",
  "                \"body-lg\": [",
  "                        \"18px\",",
  "                        {",
  "                                \"lineHeight\": \"1.6\",",
  "                                \"fontWeight\": \"400\"",
  "                        }",
  "                ],",
  "                \"label-sm\": [",
  "                        \"12px\",",
  "                        {",
  "                                \"lineHeight\": \"1.4\",",
  "                                \"letterSpacing\": \"0.05em\",",
  "                                \"fontWeight\": \"600\"",
  "                        }",
  "                ],",
  "                \"headline-lg-mobile\": [",
  "                        \"28px\",",
  "                        {",
  "                                \"lineHeight\": \"1.2\",",
  "                                \"fontWeight\": \"600\"",
  "                        }",
  "                ],",
  "                \"display-lg\": [\"48px\", { \"lineHeight\": \"1.1\", \"letterSpacing\": \"-0.02em\", \"fontWeight\": \"600\" }],",
  "                \"code-sm\": [\"13px\", { \"lineHeight\": \"1.4\", \"fontWeight\": \"400\" }],",
  "                \"label-caps\": [\"12px\", { \"lineHeight\": \"1.0\", \"letterSpacing\": \"0.1em\", \"fontWeight\": \"500\" }],",
  "                \"display-lg-mobile\": [\"32px\", { \"lineHeight\": \"1.2\", \"fontWeight\": \"600\" }]",
  "        }",
  "},",
  "    },",
  "  }",
  "</script>",
  "</head>",
  "<body class=\"bg-surface-container-low text-on-surface font-body-md min-h-screen overflow-hidden flex selection:bg-primary-container selection:text-on-primary-container max-w-[1280px] mx-auto shadow-2xl relative items-center justify-center bg-slate-200\"><div class=\"w-[1280px] h-[1024px] bg-surface-container-low text-on-surface font-body-md relative overflow-hidden shadow-2xl flex selection:bg-primary-container selection:text-on-primary-container shrink-0\">",
  "<!-- Interactive Antigravity Background -->",
  "<canvas class=\"absolute inset-0 z-0 pointer-events-none opacity-60\" id=\"antigravity-canvas\"></canvas>",
  "<!-- SideNavBar -->",
  "<aside class=\"dewdrop-panel rounded-r-[32px] absolute left-0 top-0 h-full flex flex-col p-4 z-40 w-64 mix-blend-normal\">",
  "<div class=\"mb-10 px-4 mt-6\">",
  "<button class=\"flex items-center gap-2 text-on-surface-variant hover:text-primary-container transition-colors mb-6 font-label-md group\">",
  "<span class=\"material-symbols-outlined group-hover:-translate-x-1 transition-transform\" data-icon=\"arrow_back\">arrow_back</span>",
  "        Back to Portal",
  "      </button>",
  "<h1 class=\"font-headline-md text-headline-md text-primary-container\">Neural Synthesis</h1>",
  "<p class=\"font-label-sm text-label-sm text-on-surface-variant mt-2 tracking-widest uppercase\">Active Project</p>",
  "</div>",
  "<nav class=\"flex-1 space-y-2\">",
  "<a class=\"flex items-center gap-4 px-4 py-3 bg-primary/10 text-primary-container border-l-2 border-primary-container transition-colors duration-200 ease-in-out\" href=\"#\">",
  "<span class=\"material-symbols-outlined\" data-icon=\"folder_open\">folder_open</span>",
  "<span class=\"font-label-md text-label-md\">Project Files</span>",
  "</a>",
  "<a class=\"flex items-center gap-4 px-4 py-3 text-on-surface-variant hover:bg-black/5 hover:text-on-surface transition-colors duration-200 ease-in-out\" href=\"#\">",
  "<span class=\"material-symbols-outlined\" data-icon=\"terminal\">terminal</span>",
  "<span class=\"font-label-md text-label-md\">Execution Logs</span>",
  "</a>",
  "</nav>",
  "<div class=\"pt-6 border-t border-white/40 space-y-2\">",
  "<a class=\"flex items-center gap-4 px-4 py-3 text-on-surface-variant hover:bg-black/5 hover:text-on-surface transition-colors duration-200 ease-in-out\" href=\"#\">",
  "<span class=\"material-symbols-outlined\" data-icon=\"description\">description</span>",
  "<span class=\"font-label-md text-label-md\">Docs</span>",
  "</a>",
  "<a class=\"flex items-center gap-4 px-4 py-3 text-on-surface-variant hover:bg-black/5 hover:text-on-surface transition-colors duration-200 ease-in-out\" href=\"#\">",
  "<span class=\"material-symbols-outlined\" data-icon=\"help\">help</span>",
  "<span class=\"font-label-md text-label-md\">Help</span>",
  "</a>",
  "</div>",
  "</aside>",
  "<!-- Main Content Area -->",
  "<main class=\"ml-64 relative z-10 flex-1 flex flex-col h-full overflow-hidden mix-blend-normal\">",
  "<!-- TopNavBar -->",
  "<header class=\"dewdrop-panel rounded-[32px] mx-6 mt-4 flex justify-between items-center px-10 h-20 z-50 mix-blend-normal shrink-0\">",
  "<div class=\"flex items-center gap-8\">",
  "<span class=\"font-headline-lg text-headline-lg text-primary-container\">AetherFlow</span>",
  "<div class=\"relative group hidden lg:block\">",
  "<span class=\"absolute inset-y-0 left-3 flex items-center text-on-surface-variant\">",
  "<span class=\"material-symbols-outlined text-[20px]\" data-icon=\"search\">search</span>",
  "</span>",
  "<input class=\"bg-white/50 border border-white/40 rounded-full py-2 pl-10 pr-4 text-body-md text-on-surface focus:outline-none focus:ring-2 focus:ring-primary-container/50 w-64 transition-all duration-300 placeholder:text-on-surface-variant\" placeholder=\"Search missions...\" type=\"text\"/>",
  "</div>",
  "</div>",
  "<div class=\"flex items-center gap-6\">",
  "<button class=\"text-on-surface-variant hover:text-primary-container transition-colors\">",
  "<span class=\"material-symbols-outlined\" data-icon=\"notifications\">notifications</span>",
  "</button>",
  "<button class=\"text-on-surface-variant hover:text-primary-container transition-colors\">",
  "<span class=\"material-symbols-outlined\" data-icon=\"settings\">settings</span>",
  "</button>",
  "<div class=\"h-10 w-10 rounded-full border border-primary-container/30 p-0.5\">",
  "<img alt=\"User profile avatar\" class=\"w-full h-full rounded-full object-cover\" src=\"https://lh3.googleusercontent.com/aida-public/AB6AXuBrEfoN78dbm_0oO6cD7avcVWtOMaurxk1RHKGsIwisIIWz-v0quc7WOhufiMdY0Gby92spgYq68FpZ1el_nZh4sphAlQm11JZhakUJPJ2x0DGjZLbo1pg5Om08pj45R4RdQUK8WFm_64dmPDMnLj9VSvT-Ln4YjJUrL9EO5mzZlni70-aKudS_2srSt9jlNamsvVXIPkSYIvFX0IoblfzUta9LhyLJrQn8pfGhEBUyK1oK7HNmWbsvDLEVNtKbC6WtPclM5drtPLGI\"/>",
  "</div>",
  "</div>",
  "</header>",
  "<!-- Content Canvas -->",
  "<div class=\"flex-1 overflow-y-auto p-10 custom-scrollbar relative z-10 mix-blend-normal\">",
  "<div class=\"max-w-[1440px] mx-auto space-y-gutter\">",
  "<div class=\"flex flex-col md:flex-row md:items-end justify-between gap-stack-lg mb-8\">",
  "<div>",
  "<p class=\"font-label-sm text-label-sm text-primary-container uppercase tracking-widest mb-2\">Operational Overview</p>",
  "<h2 class=\"font-display text-display text-on-surface mb-2\">Active Mission Hub</h2>",
  "</div>",
  "<button class=\"luminous-button px-8 py-3 rounded-2xl flex items-center gap-2 text-on-primary font-label-md text-label-md\">",
  "<span class=\"material-symbols-outlined\" data-icon=\"add\">add</span>",
  "            Initialize New Mission",
  "          </button>",
  "</div>",
  "<div class=\"grid grid-cols-1 md:grid-cols-12 gap-gutter\">",
  "<div class=\"md:col-span-8 dewdrop-card rounded-[32px] p-stack-lg flex flex-col gap-stack-lg relative overflow-hidden group\">",
  "<div class=\"absolute top-0 right-0 w-64 h-64 bg-primary/20 blur-[100px] rounded-full -translate-y-1/2 translate-x-1/2\"></div>",
  "<div class=\"flex justify-between items-start z-10\">",
  "<div>",
  "<span class=\"bg-primary/10 text-primary-container text-xs font-label-caps px-2 py-1 rounded border border-primary/20 tracking-widest\">PRIORITY ALPHA</span>",
  "<h3 class=\"font-headline-lg text-headline-lg mt-stack-sm text-on-surface\">Project: Neural Synthesis</h3>",
  "<p class=\"text-on-surface-variant font-body-md mt-2\">Cross-platform integration for autonomous creative workflows.</p>",
  "</div>",
  "<div class=\"text-right\">",
  "<span class=\"font-code-sm text-code-sm text-primary-container uppercase tracking-widest\">EST. COMPLETION: 4H 12M</span>",
  "</div>",
  "</div>",
  "<div class=\"h-48 w-full flex items-end gap-2 px-stack-sm py-stack-md z-10\">",
  "<div class=\"flex-1 bg-primary/20 hover:bg-primary/40 transition-all rounded-t-sm\" style=\"height: 40%\"></div>",
  "<div class=\"flex-1 bg-primary/30 hover:bg-primary/50 transition-all rounded-t-sm\" style=\"height: 60%\"></div>",
  "<div class=\"flex-1 bg-primary/40 hover:bg-primary/60 transition-all rounded-t-sm\" style=\"height: 35%\"></div>",
  "<div class=\"flex-1 bg-primary/50 hover:bg-primary/70 transition-all rounded-t-sm\" style=\"height: 85%\"></div>",
  "<div class=\"flex-1 bg-primary/60 hover:bg-primary/80 transition-all rounded-t-sm\" style=\"height: 70%\"></div>",
  "<div class=\"flex-1 bg-primary/30 hover:bg-primary/50 transition-all rounded-t-sm\" style=\"height: 95%\"></div>",
  "<div class=\"flex-1 bg-primary/40 hover:bg-primary/60 transition-all rounded-t-sm\" style=\"height: 45%\"></div>",
  "</div>",
  "<div class=\"flex items-center justify-between z-10 mt-auto pt-4\">",
  "<div class=\"flex -space-x-3\">",
  "<img alt=\"Agent Avatar\" class=\"w-10 h-10 rounded-full border-2 border-white bg-secondary/10 p-1\" src=\"https://lh3.googleusercontent.com/aida-public/AB6AXuAFi56UWulTz0ywCIFf-K3GRr9tlX4IDQ9eWSjDkJ-LS-iUUS7rjVVZZj19ZfdjvHmXDiMvLag-4u0A7WaEW5eDPIfqJJ4vJPU65Ro9jEqzybwwCFgscJHB4K08XlEcJPX7fZ7r33KhbgpEBN6ardiaesT0l2Vgc8GN__Wal2K7hofH0xcNuP_7kWtL-TXalgZ6treUGaree0YakQ0ZEs1AQxfm0XJlebYTz0ECknIyVmr13OMRspYQxrxNp4jfF8yVw0dqZc9FRF07\"/>",
  "<img alt=\"Agent Avatar\" class=\"w-10 h-10 rounded-full border-2 border-white bg-tertiary/10 p-1\" src=\"https://lh3.googleusercontent.com/aida-public/AB6AXuBd06MMMWQ9uBw2IuB62MChXIVRrwhJPlomuHiN0Kd8D6ERpJUxn29HAmhffluX7lIOfGKHA_NKn3lulBZc7eO1d9ToH2t5cSy3bZdqENmmHssFfMCXULjZnPfZIZludfT56a7ahoCNX1i97VCivGAZyCwmgdljWk5_XPSanOEkvKZMc0RZd6Jh0yg62diKlgxtN6XrCq8NZ7U_DOWYpyZTFspmFmdhSw1zjg6QCqdyBpPIG2Uvg-euHPP2Oj_1TT9Ds3ytt5G2-N0L\"/>",
  "<img alt=\"Agent Avatar\" class=\"w-10 h-10 rounded-full border-2 border-white bg-primary/10 p-1\" src=\"https://lh3.googleusercontent.com/aida-public/AB6AXuBXCTCBJ3wkStRsxh-XILSVRn-DDigzTAYKjGQ_vLdemXWLpQ_WDyv_n6eHI9omcX7r9087-V1G2kYBIcRz9P8AKvJ1dtOgWqsm47WMM-GFnq85LI0vNogF9oO4xZ6Gu0mXjXDIPbMULxoWYpbiznL8VKrX4fe8AWloqPfDoFdHuwmvz0biZhoYhZHV3ivYILBLWR82oTHuSTHpnAPfMEeGWCjz6w25Ux9RKtzKltRa7l5LfbSdqmjjQAcyfufmrRITCdH6F7qitKiQ\"/>",
  "<div class=\"w-10 h-10 rounded-full border-2 border-white bg-surface-container flex items-center justify-center font-label-caps text-on-surface-variant text-[10px]\">+4</div>",
  "</div>",
  "<div class=\"flex items-center gap-stack-md\">",
  "<div class=\"text-right\">",
  "<span class=\"block font-label-caps text-on-surface-variant text-[10px] tracking-widest uppercase\">CURRENT LOAD</span>",
  "<span class=\"font-headline-lg text-headline-lg text-on-surface\">78%</span>",
  "</div>",
  "<div class=\"w-px h-10 bg-black/10\"></div>",
  "<button class=\"p-3 bg-black/5 rounded-2xl hover:bg-black/10 transition-all active:scale-95 text-on-surface-variant hover:text-on-surface\">",
  "<span class=\"material-symbols-outlined text-[20px]\" data-icon=\"open_in_new\">open_in_new</span>",
  "</button>",
  "</div>",
  "</div>",
  "</div>",
  "<div class=\"md:col-span-4 grid grid-rows-2 gap-gutter\">",
  "<div class=\"dewdrop-card rounded-[32px] p-stack-lg flex flex-col justify-center relative overflow-hidden group\">",
  "<div class=\"absolute inset-0 bg-gradient-to-br from-secondary/10 to-transparent opacity-0 group-hover:opacity-100 transition-opacity\"></div>",
  "<div class=\"flex items-center gap-stack-md mb-4\">",
  "<div class=\"w-10 h-10 rounded-2xl bg-secondary/10 flex items-center justify-center text-secondary\">",
  "<span class=\"material-symbols-outlined\" data-icon=\"bolt\">bolt</span>",
  "</div>",
  "<span class=\"font-label-sm text-label-sm text-secondary uppercase tracking-widest\">Global Velocity</span>",
  "</div>",
  "<h4 class=\"font-display-lg text-display-lg-mobile text-secondary\">14.8 <span class=\"text-body-md font-normal opacity-50\">ops/s</span></h4>",
  "<div class=\"mt-4 h-1 w-full bg-black/5 rounded-full overflow-hidden\">",
  "<div class=\"h-full bg-secondary w-3/4 animate-pulse\"></div>",
  "</div>",
  "</div>",
  "<div class=\"dewdrop-card rounded-[32px] p-stack-lg flex flex-col justify-center relative overflow-hidden group\">",
  "<div class=\"absolute inset-0 bg-gradient-to-br from-tertiary/10 to-transparent opacity-0 group-hover:opacity-100 transition-opacity\"></div>",
  "<div class=\"flex items-center gap-stack-md mb-4\">",
  "<div class=\"w-10 h-10 rounded-2xl bg-tertiary/10 flex items-center justify-center text-tertiary\">",
  "<span class=\"material-symbols-outlined\" data-icon=\"shield\">shield</span>",
  "</div>",
  "<span class=\"font-label-sm text-label-sm text-tertiary uppercase tracking-widest\">System Integrity</span>",
  "</div>",
  "<h4 class=\"font-display-lg text-display-lg-mobile text-tertiary\">99.98<span class=\"text-body-md font-normal opacity-50\">%</span></h4>",
  "<div class=\"mt-4 h-1 w-full bg-black/5 rounded-full overflow-hidden\">",
  "<div class=\"h-full bg-tertiary w-full\"></div>",
  "</div>",
  "</div>",
  "</div>",
  "<div class=\"md:col-span-4 dewdrop-card rounded-[32px] p-stack-lg flex flex-col h-[500px]\">",
  "<div class=\"flex justify-between items-center mb-stack-lg\">",
  "<h3 class=\"font-headline-md text-headline-md text-on-surface\">Orchestra Feed</h3>",
  "<button class=\"text-on-surface-variant hover:text-primary-container transition-colors\">",
  "<span class=\"material-symbols-outlined cursor-pointer\" data-icon=\"more_vert\">more_vert</span>",
  "</button>",
  "</div>",
  "<div class=\"flex-1 overflow-y-auto space-y-stack-md pr-2 custom-scrollbar\">",
  "<div class=\"p-4 rounded-2xl bg-white/40 border border-white/30 flex gap-4 group hover:bg-white/60 transition-all\">",
  "<div class=\"w-1 bg-primary-container rounded-full shrink-0\"></div>",
  "<div class=\"flex-1\">",
  "<p class=\"text-body-md font-medium text-on-surface\">Agent <span class=\"text-primary-container\">Vector-7</span> assigned to Research Task</p>",
  "<span class=\"text-xs text-on-surface-variant font-code-sm mt-1 block\">2m ago • Project: Synthesis</span>",
  "</div>",
  "</div>",
  "<div class=\"p-4 rounded-2xl bg-white/40 border border-white/30 flex gap-4 group hover:bg-white/60 transition-all\">",
  "<div class=\"w-1 bg-secondary rounded-full shrink-0\"></div>",
  "<div class=\"flex-1\">",
  "<p class=\"text-body-md font-medium text-on-surface\">Payload Validation <span class=\"text-secondary\">Complete</span></p>",
  "<span class=\"text-xs text-on-surface-variant font-code-sm mt-1 block\">12m ago • Project: Data-Core</span>",
  "</div>",
  "</div>",
  "<div class=\"p-4 rounded-2xl bg-white/40 border border-white/30 flex gap-4 group hover:bg-white/60 transition-all\">",
  "<div class=\"w-1 bg-tertiary rounded-full shrink-0\"></div>",
  "<div class=\"flex-1\">",
  "<p class=\"text-body-md font-medium text-on-surface\">Memory Overflow <span class=\"text-error\">Warning</span> in Core-Node-9</p>",
  "<span class=\"text-xs text-on-surface-variant font-code-sm mt-1 block\">24m ago • System-Wide</span>",
  "</div>",
  "</div>",
  "<div class=\"p-4 rounded-2xl bg-white/40 border border-white/30 flex gap-4 group hover:bg-white/60 transition-all\">",
  "<div class=\"w-1 bg-primary-container rounded-full shrink-0\"></div>",
  "<div class=\"flex-1\">",
  "<p class=\"text-body-md font-medium text-on-surface\">Autonomous Pivot initiated by <span class=\"text-primary-container\">Zeta-Alpha</span></p>",
  "<span class=\"text-xs text-on-surface-variant font-code-sm mt-1 block\">45m ago • Task: Optimization</span>",
  "</div>",
  "</div>",
  "</div>",
  "</div>",
  "<div class=\"md:col-span-8 grid grid-cols-1 sm:grid-cols-2 gap-gutter\">",
  "<div class=\"dewdrop-card rounded-[32px] p-stack-lg flex flex-col gap-stack-md group\">",
  "<div class=\"flex justify-between items-center mb-2\">",
  "<h4 class=\"font-headline-md text-headline-md text-on-surface\">Aether-Ops</h4>",
  "<span class=\"material-symbols-outlined text-primary-container\" data-icon=\"sensors\" style=\"font-variation-settings: 'FILL' 1;\">sensors</span>",
  "</div>",
  "<div class=\"flex flex-wrap gap-2 mb-4\">",
  "<span class=\"agent-pill border-l-primary-container bg-white/40 px-3 py-1.5 rounded text-[10px] font-label-caps text-on-surface-variant tracking-widest\">AGENT_V14</span>",
  "<span class=\"agent-pill border-l-secondary bg-white/40 px-3 py-1.5 rounded text-[10px] font-label-caps text-on-surface-variant tracking-widest\">SCRAPER_BOT</span>",
  "</div>",
  "<div class=\"mt-auto pt-4\">",
  "<div class=\"flex justify-between text-xs mb-2\">",
  "<span class=\"text-on-surface-variant\">Execution: 42%</span>",
  "<span class=\"text-primary-container\">Active</span>",
  "</div>",
  "<div class=\"h-1.5 w-full bg-black/5 rounded-full overflow-hidden\">",
  "<div class=\"h-full bg-primary-container w-[42%]\"></div>",
  "</div>",
  "</div>",
  "</div>",
  "<div class=\"dewdrop-card rounded-[32px] p-stack-lg flex flex-col gap-stack-md group\">",
  "<div class=\"flex justify-between items-center mb-2\">",
  "<h4 class=\"font-headline-md text-headline-md text-on-surface\">Market-Oracle</h4>",
  "<span class=\"material-symbols-outlined text-secondary\" data-icon=\"auto_graph\" style=\"font-variation-settings: 'FILL' 1;\">auto_graph</span>",
  "</div>",
  "<div class=\"flex flex-wrap gap-2 mb-4\">",
  "<span class=\"agent-pill border-l-tertiary bg-white/40 px-3 py-1.5 rounded text-[10px] font-label-caps text-on-surface-variant tracking-widest\">PREDICT_MOD</span>",
  "<span class=\"agent-pill border-l-primary-container bg-white/40 px-3 py-1.5 rounded text-[10px] font-label-caps text-on-surface-variant tracking-widest\">DATA_VIZ</span>",
  "</div>",
  "<div class=\"mt-auto pt-4\">",
  "<div class=\"flex justify-between text-xs mb-2\">",
  "<span class=\"text-on-surface-variant\">Execution: 89%</span>",
  "<span class=\"text-secondary\">Refining</span>",
  "</div>",
  "<div class=\"h-1.5 w-full bg-black/5 rounded-full overflow-hidden\">",
  "<div class=\"h-full bg-secondary w-[89%]\"></div>",
  "</div>",
  "</div>",
  "</div>",
  "</div>",
  "</div>",
  "</div>",
  "</div>",
  "</main>",
  "</div></body></html>"
].join("\r\n");

export function ProjectPage() {
  return (
    <iframe
      title="Project"
      srcDoc={pageHtml}
      sandbox="allow-scripts allow-same-origin allow-popups allow-forms"
      style={{ width: "100%", height: "100vh", border: 0, display: "block" }}
    />
  );
}

export default ProjectPage;
