import type { AgentProfileCatalogItem } from './agentProfileCatalogTypes';

/* ═══════════════════════════════════════════════════════════════════════
   agentProfileCatalogData — residual fixture extract from agentProfileCatalog
   (#652). Static AgentProfile catalog rows only.
   ═══════════════════════════════════════════════════════════════════════ */

export const AGENT_PROFILE_CATALOG: AgentProfileCatalogItem[] = [
  {
    id: 'builder-agent',
    name: 'Builder',
    role: '代码实现',
    description: '把需求拆成小步实现，输出 diff、测试证据和交接摘要。',
    visibility: 'fixture',
    source: 'fixture',
    category: '研发',
    avatarRef: 'agenthub:avatar/builder',
    avatarColor: 'var(--role-builder)',
    runtime: {
      runtimeId: 'claude-code',
      label: 'Claude Code',
      provider: 'TokenDance Gateway',
      model: 'DeepSeek-V4-Pro',
      reasoning: 'high',
      adapterMode: 'cli',
    },
    configuration: {
      mode: 'Plan -> Code',
      scope: '当前项目',
      state: 'running',
      skills: ['Read File', 'Write File', 'Shell', 'Git Diff'],
      mcpServers: ['filesystem', 'github'],
      toolAllowlist: ['Read File', 'Write File', 'Shell', 'Git Diff', 'Browser Screenshot'],
      approval: {
        mode: 'workspace-write',
        summary: '写文件和 Shell 默认进入确认队列',
        riskRules: [
          { match: 'read workspace files', decision: 'allow' },
          { match: 'write workspace files', decision: 'require-approval' },
          { match: 'production deploy', decision: 'deny' },
        ],
      },
      memory: {
        sources: ['agents-md', 'project-memory', 'thread-context'],
        retention: 'project-policy',
        summary: '读取 AGENTS.md、项目记忆和当前 Thread 上下文',
      },
      targetPreferences: ['local-edge', 'remote-edge'],
    },
    market: {
      featured: true,
      detail: '适合 48h 内可验收的小切片、focused tests 和代码交接。',
      installLabel: '安装 Builder',
    },
  },
  {
    id: 'reviewer-agent',
    name: 'Reviewer',
    role: '审查与验收',
    description: '从风险、回归、测试缺口和合同边界审查 Agent 输出。',
    visibility: 'fixture',
    source: 'fixture',
    category: '测试',
    avatarRef: 'agenthub:avatar/reviewer',
    avatarColor: 'var(--role-reviewer)',
    runtime: {
      runtimeId: 'claude-code',
      label: 'Claude Code',
      provider: 'TokenDance Gateway',
      model: 'DeepSeek-V4-Pro',
      reasoning: 'high',
      adapterMode: 'cli',
    },
    configuration: {
      mode: 'Review',
      scope: '当前项目',
      state: 'ready',
      skills: ['Read File', 'Git Diff', 'Browser Screenshot'],
      mcpServers: ['github'],
      toolAllowlist: ['Read File', 'Git Diff', 'Browser Screenshot'],
      approval: {
        mode: 'read-only',
        summary: '只读默认允许，写入和执行命令禁止',
        riskRules: [
          { match: 'read workspace files', decision: 'allow' },
          { match: 'write workspace files', decision: 'deny' },
          { match: 'execute command', decision: 'require-approval' },
        ],
      },
      memory: {
        sources: ['agents-md', 'thread-context', 'artifact-summary'],
        retention: 'thread-only',
        summary: '只保留本轮审查 Thread 和产物摘要',
      },
      targetPreferences: ['local-edge', 'hub-relay'],
    },
    market: {
      featured: true,
      detail: '适合 PR 前 focused review、diff 风险列表和验收证据检查。',
      installLabel: '安装 Reviewer',
    },
  },
  {
    id: 'researcher-agent',
    name: 'Researcher',
    role: '资料研究',
    description: '整理外部资料、引用和文档库线索，不直接执行写入。',
    visibility: 'fixture',
    source: 'fixture',
    category: '文档',
    avatarRef: 'agenthub:avatar/researcher',
    avatarColor: 'var(--role-researcher)',
    runtime: {
      runtimeId: 'codex',
      label: 'Codex',
      provider: 'OpenAI Compatible API',
      model: 'gpt-5-codex',
      reasoning: 'medium',
      adapterMode: 'cli',
    },
    configuration: {
      mode: 'Research',
      scope: '文档库',
      state: 'idle',
      skills: ['Web 摘要', '文档库', '引用整理'],
      mcpServers: ['browser-search'],
      toolAllowlist: ['Read File', 'Browser Screenshot'],
      approval: {
        mode: 'approval-required',
        summary: '外部访问和资料写入前确认',
        riskRules: [
          { match: 'read docs', decision: 'allow' },
          { match: 'external fetch', decision: 'require-approval' },
          { match: 'write files', decision: 'require-approval' },
        ],
      },
      memory: {
        sources: ['project-memory', 'thread-context', 'artifact-summary'],
        retention: 'project-policy',
        summary: '优先项目记忆、Thread 结论和引用摘要',
      },
      targetPreferences: ['hub-relay', 'fixture'],
    },
    market: {
      featured: false,
      detail: '适合竞品调研、引用整理、会议结论和知识库索引。',
      installLabel: '安装 Researcher',
    },
  },
  {
    id: 'deployer-agent',
    name: 'Deployer',
    role: '预览与发布',
    description: '整理发布检查、预览证据、产物归档和回滚清单。',
    visibility: 'fixture',
    source: 'fixture',
    category: '发布',
    avatarRef: 'agenthub:avatar/deployer',
    avatarColor: 'var(--role-deployer)',
    runtime: {
      runtimeId: 'opencode',
      label: 'OpenCode',
      provider: 'TokenDance Gateway',
      model: 'DeepSeek-V4-Pro',
      reasoning: 'medium',
      adapterMode: 'cli',
    },
    configuration: {
      mode: 'Deploy',
      scope: '当前项目',
      state: 'waiting',
      skills: ['Shell', '构建', '预览', '产物归档'],
      mcpServers: ['filesystem'],
      toolAllowlist: ['Read File', 'Write File', 'Shell', 'Git Diff', 'Browser Screenshot'],
      approval: {
        mode: 'approval-required',
        summary: '构建可确认执行，生产发布默认禁止',
        riskRules: [
          { match: 'build preview', decision: 'require-approval' },
          { match: 'archive artifacts', decision: 'require-approval' },
          { match: 'production deploy', decision: 'deny' },
        ],
      },
      memory: {
        sources: ['agents-md', 'artifact-summary', 'fixture'],
        retention: 'thread-only',
        summary: '本轮产物摘要和发布检查，不持久保存密钥',
      },
      targetPreferences: ['local-edge', 'cloud-edge'],
    },
    market: {
      featured: false,
      detail: '适合上线前检查、预览 URL、归档包和回滚摘要。',
      installLabel: '安装 Deployer',
    },
  },
];
